Repository codestates-seb/seb40_main_015, pull requests merged in 2022-11, with the labels that each got.

#4 [BE] Feat : 책 엔티티 생성
  .idea/.gitignore
  backend/dongnebook/src/main/java/com/dongnebook/domain/book/book.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/book/domain/Book.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/book/domain/BookState.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/book/domain/Money.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/book/ui/BookController.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/member/controller/member.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/member/ui/member.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/model/Location.java
Labels: 벡엔드, 기능

#5 [BE] Feat : 공통예외처리
  backend/dongnebook/src/main/java/com/dongnebook/domain/book/domain/Book.java
  backend/dongnebook/src/main/java/com/dongnebook/global/error/ErrorResponse.java
  backend/dongnebook/src/main/java/com/dongnebook/global/error/GlobalExceptionHandler.java
  backend/dongnebook/src/main/java/com/dongnebook/global/error/exception/BusinessException.java
  backend/dongnebook/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
Labels: 벡엔드, 기능, 리팩토링

#10 [BE] Bug : @builder.default 제거
  backend/dongnebook/build/classes/java/main/com/dongnebook/domain/MemberAPI.class
  backend/dongnebook/build/classes/java/main/com/dongnebook/domain/book/book.class
  backend/dongnebook/build/classes/java/main/com/dongnebook/domain/member/controller/member.class
  backend/dongnebook/build/classes/java/main/com/dongnebook/domain/member/repository/memeberrepository.class
  backend/dongnebook/src/main/java/com/dongnebook/domain/book/domain/Book.java
Labels: 벡엔드, 버그

#13 [BE] Member 엔티티 작성 외
  backend/dongnebook/build.gradle
  backend/dongnebook/build/classes/java/main/com/dongnebook/domain/rental/rental.class
  backend/dongnebook/src/main/java/com/dongnebook/domain/MemberAPI.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/helloSample/ui/HelloController.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/member/domain/Member.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/member/dto/Request/MemberLoginRequest.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/member/dto/Request/MemberRegisterRequest.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/member/repository/MemberRepository.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/rental/Rental.java
  backend/dongnebook/src/main/java/com/dongnebook/global/config/security/SecurityConfigurationV1.java
  backend/dongnebook/src/test/java/com/dongnebook/DongnebookApplicationTests.java
  backend/dongnebook/src/test/java/com/dongnebook/domain/helloSample/ui/HelloControllerTest.java
Labels: 벡엔드, 기능, 리팩토링, 버그

#11 [BE] Feat : 책삭제
  backend/dongnebook/src/main/java/com/dongnebook/domain/book/application/BookService.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/book/domain/Book.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/book/domain/BookState.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/book/exception/BookNotFoundException.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/book/exception/NotRentableException.java
  backend/dongnebook/src/main/java/com/dongnebook/domain/book/ui/BookController.java
  backend/dongnebook/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
Labels: 벡엔드, 기능

#9 [FE] feat : 상인정보, 대여내역페이지 레이아웃 구현
  frontend/src/components/common/NavTemp.tsx
  frontend/src/pages/BooksListPage.tsx
  frontend/src/pages/HistoryPage.tsx
  frontend/src/pages/LayoutTemp.tsx
  frontend/src/pages/LendHistoryPage.tsx
  frontend/src/pages/MerchantPage.tsx
  frontend/src/pages/RentHistoryPage.tsx
  frontend/src/styles/globalStyles.ts
Labels: 프론트엔드, 기능

#35 [FE] Fix : 라우팅 탭 관련 부분 제거
  frontend/src/pages/BookingListPage.tsx
  frontend/src/pages/BooksListPage.tsx
  frontend/src/pages/HistoryPage.tsx
  frontend/src/pages/LendHistoryPage.tsx
  frontend/src/pages/MerchantPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/pages/RentHistoryPage.tsx
  frontend/src/pages/ReviewListPage.tsx
  frontend/src/pages/WishListPage.tsx
  frontend/src/pages/index.tsx
  frontend/src/router/Router.tsx
Labels: 프론트엔드, 기능

#38 [FE] Feat : 동네북 로고 추가
  frontend/src/assets/image/동네북 로고 1.png
  frontend/src/assets/image/동네북 로고 2.png
  frontend/src/assets/image/동네북 로고3.png
  frontend/src/assets/image/동네북 로고4.png
Labels: 프론트엔드

#39 Refactor/be/폴더구조변경
  .idea/.gitignore
  backend/.gitignore
  backend/.idea/gradle.xml
  backend/build.gradle
  backend/dongnebook/.gitignore
  backend/dongnebook/build/classes/java/main/com/dongnebook/DongnebookApplication.class
  backend/dongnebook/build/classes/java/main/com/dongnebook/domain/rental/rental.class
  backend/dongnebook/src/main/resources/application.yml
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/src/main/java/com/dongnebook/DongnebookApplication.java
  backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
  backend/src/main/java/com/dongnebook/domain/book/domain/Book.java
  backend/src/main/java/com/dongnebook/domain/book/domain/BookState.java
  backend/src/main/java/com/dongnebook/domain/book/domain/Money.java
  backend/src/main/java/com/dongnebook/domain/book/dto/Request/BookRegisterRequest.java
  backend/src/main/java/com/dongnebook/domain/book/exception/BookNotFoundException.java
  backend/src/main/java/com/dongnebook/domain/book/exception/NotRentableException.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookRepository.java
  backend/src/main/java/com/dongnebook/domain/book/ui/BookController.java
  backend/src/main/java/com/dongnebook/domain/helloSample/ui/HelloController.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
  backend/src/main/java/com/dongnebook/domain/member/dto/Request/MemberLoginRequest.java
  backend/src/main/java/com/dongnebook/domain/member/dto/Request/MemberRegisterRequest.java
  backend/src/main/java/com/dongnebook/domain/member/exception/LocationNotCreatedYetException.java
  backend/src/main/java/com/dongnebook/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
  backend/src/main/java/com/dongnebook/domain/model/Location.java
  backend/src/main/java/com/dongnebook/domain/rental/Rental.java
  backend/src/main/java/com/dongnebook/global/config/security/SecurityConfigurationV1.java
  backend/src/main/java/com/dongnebook/global/error/ErrorResponse.java
  backend/src/main/java/com/dongnebook/global/error/GlobalExceptionHandler.java
  backend/src/main/java/com/dongnebook/global/error/exception/BusinessException.java
  backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/dongnebook/DongnebookApplicationTests.java
  backend/src/test/java/com/dongnebook/domain/helloSample/ui/HelloControllerTest.java
Labels: 벡엔드, 리팩토링

#40 [FE] Feat : navbar 수정
  frontend/src/assets/image/home.png
  frontend/src/assets/image/logo1.png
  frontend/src/assets/image/logo2.png
  frontend/src/assets/image/logo3.png
  frontend/src/assets/image/logo4.png
  frontend/src/components/common/NavTemp.tsx
Labels: 프론트엔드

#48 [BE] Refactor: Member 도메인 안 엔티티와 request dto 수정
  backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
  backend/src/main/java/com/dongnebook/domain/member/dto/Request/MemberLoginRequest.java
  backend/src/main/java/com/dongnebook/domain/member/dto/Request/MemberRegisterRequest.java
Labels: 벡엔드, 리팩토링

#51 [FE] feat : Input 공통 컴포넌트 구현, 미사용 이미지 파일 삭제
  frontend/src/assets/image/동네북 로고 1.png
  frontend/src/assets/image/동네북 로고 2.png
  frontend/src/assets/image/동네북 로고3.png
  frontend/src/assets/image/동네북 로고4.png
  frontend/src/components/common/Input.tsx
Labels: 프론트엔드, 기능

#53 [FE] Feat : Title에 이미지 추가
  frontend/src/assets/README.md
  frontend/src/components/Books/BookItem.tsx
  frontend/src/components/Buttons/LongButton.tsx
  frontend/src/components/README.md
  frontend/src/components/common/Title.tsx
  frontend/src/pages/BooksCreatePage.tsx
  frontend/src/pages/BooksPage.tsx
  frontend/src/pages/LayoutTemp.tsx
Labels: 프론트엔드, 기능

#55 [FE] Feat : 로그인 페이지 뷰 구현, theme subtitle 글자 크기 조정
  frontend/src/components/Login/LinkToSignUp.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/Login/Logo.tsx
  frontend/src/components/Login/Oauth.tsx
  frontend/src/components/Login/ThirdPartyIcon.tsx
  frontend/src/components/common/Title.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/styles/theme.ts
Labels: 프론트엔드

#56 [FE] feat : TabLists에 탭 변경 기능 추가 및 useTabs 구현
  frontend/src/components/Merchant/BookList.tsx
  frontend/src/components/Merchant/Review.tsx
  frontend/src/components/common/TabLists.tsx
  frontend/src/hooks/useTabs.ts
  frontend/src/pages/HistoryPage.tsx
  frontend/src/pages/LenderInfoPage.tsx
  frontend/src/pages/MerchantPage.tsx
  frontend/tsconfig.json
Labels: 프론트엔드, 기능

#58 [FE] Feat : 책 상세조회 페이지 html/css 구현
  frontend/src/components/common/Input.tsx
  frontend/src/components/common/Title.tsx
  frontend/src/pages/BooksCreatePage.tsx
  frontend/src/pages/BooksDetailPage.tsx
  frontend/src/pages/BooksPage.tsx
  frontend/src/pages/LayoutTemp.tsx
Labels: 프론트엔드, 기능

#59 [FE] Feat : 프로필 수정 버튼 활성화
  frontend/src/components/common/Title.tsx
  frontend/src/pages/LayoutTemp.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/ProfilePage.tsx
Labels: 프론트엔드

#60 [FE] feat : useTabs 와 TabLists 일부 수정
  frontend/src/components/common/TabLists.tsx
  frontend/src/hooks/useTabs.ts
  frontend/src/pages/MerchantPage.tsx
Labels: 프론트엔드, 기능

#52 [BE] Feat: rental 엔티티 구현
  backend/src/main/java/com/dongnebook/domain/rental/Rental.java
  backend/src/main/java/com/dongnebook/domain/rental/domain/Rental.java
Labels: 벡엔드, 기능

#57 [BE] Feat : 책 상세조회 기능 추가
  backend/build.gradle
  backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
  backend/src/main/java/com/dongnebook/domain/book/domain/Book.java
  backend/src/main/java/com/dongnebook/domain/book/domain/BookState.java
  backend/src/main/java/com/dongnebook/domain/book/dto/Request/BookRegisterRequest.java
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookDetailResponse.java
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookResponse.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookCommandRepository.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/book/ui/BookController.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
  backend/src/main/java/com/dongnebook/domain/member/dto/Request/MemberLoginRequest.java
  backend/src/main/java/com/dongnebook/domain/member/dto/Request/MemberRegisterRequest.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/BookDetailMemberResponse.java
  backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
  backend/src/main/java/com/dongnebook/domain/model/BaseTimeEntity.java
  backend/src/main/java/com/dongnebook/global/config/QueryDslConfig.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/dongnebook/domain/test.java
Labels: 벡엔드, 기능

#69 [FE] feat : 대여목록 빌려준 책 구현
  frontend/src/components/History/LendBookLists.tsx
  frontend/src/components/History/LendStatusButton.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/History/RentStatusButton.tsx
  frontend/src/components/History/SortButton.tsx
  frontend/src/components/Merchant/BookList.tsx
  frontend/src/components/common/Button.tsx
  frontend/src/components/common/TabLists.tsx
  frontend/src/components/common/Title.tsx
  frontend/src/pages/HistoryPage.tsx
  frontend/src/pages/LayoutTemp.tsx
  frontend/src/pages/MerchantPage.tsx
  frontend/src/styles/globalStyles.ts
  frontend/src/styles/theme.ts
  frontend/src/utils/convertDate.ts
Labels: 프론트엔드, 기능

#70 [FE] feat : Title 로고 추가
  frontend/src/components/common/Title.tsx
Labels: 프론트엔드

#72 [FE] feat : hero section
  frontend/src/assets/image/iphone.png
  frontend/src/components/common/Title.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/router/Router.tsx
Labels: 프론트엔드

#75 [FE] feat : 회원가입 페이지 뷰 완성
  frontend/src/components/Login/LinkToSignUp.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/Login/Logo.tsx
  frontend/src/components/SignUp/Bubble.tsx
  frontend/src/components/SignUp/Clause.tsx
  frontend/src/components/SignUp/SignUpForm.tsx
  frontend/src/components/common/LinkToSign.tsx
  frontend/src/components/common/Oauth.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/SignupPage.tsx
Labels: 프론트엔드, 기능

#76 [FE] Feat: 책 대여페이지 스타일 구현
  frontend/src/components/Books/BookCalendar.tsx
  frontend/src/components/Books/BookElements.tsx
  frontend/src/pages/BooksBookingPage.tsx
  frontend/src/pages/BooksCreatePage.tsx
  frontend/src/pages/BooksDetailPage.tsx
  frontend/src/pages/BooksRentalPage.tsx
Labels: 프론트엔드

#77 [FE] feat : 레이아웃 변경
  frontend/src/components/History/LendBookLists.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/History/RentStatusButton.tsx
  frontend/src/components/History/SortButton.tsx
  frontend/src/components/common/TabLists.tsx
  frontend/src/pages/HistoryPage.tsx
Labels: 프론트엔드

#73 [BE] Feat : 도서 검색 - 지도에 구획별 책 갯수를 뿌려준다. v1
  backend/src/main/java/com/dongnebook/DongnebookApplication.java
  backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
  backend/src/main/java/com/dongnebook/domain/book/dto/Request/SectorBookCountRequest.java
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookSectorCountResponse.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/book/ui/BookController.java
  backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
  backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
  backend/src/main/java/com/dongnebook/domain/model/Location.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/dongnebook/Location/locationTest.java
Labels: 벡엔드, 기능

#71 [BE] feat : 대여하기 기능 구현
  backend/src/main/java/com/dongnebook/DongnebookApplication.java
  backend/src/main/java/com/dongnebook/domain/member/exception/MemberNotFoundException.java
  backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
  backend/src/main/java/com/dongnebook/domain/rental/domain/Rental.java
  backend/src/main/java/com/dongnebook/domain/rental/domain/RentalState.java
  backend/src/main/java/com/dongnebook/domain/rental/dto/Request/RentalRegisterRequest.java
  backend/src/main/java/com/dongnebook/domain/rental/repository/RentalRepository.java
  backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java
  backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
Labels: 벡엔드, 기능

#74 [BE] Feat : 유효성 검증과 중복확인을 포함한 회원가입 기능 구현
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
  backend/src/main/java/com/dongnebook/domain/member/dto/request/MemberLoginRequest.java
  backend/src/main/java/com/dongnebook/domain/member/dto/request/MemberRegisterRequest.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberExistsCheckResponse.java
  backend/src/main/java/com/dongnebook/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
  backend/src/main/java/com/dongnebook/global/config/security/SecurityConfigurationV1.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/SecurityConfigurationV1.java
  backend/src/main/resources/application.yml
Labels: 벡엔드, 기능

#78 [FE] design : 로그인, 회원가입 페이지 레이아웃 조정
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/Login/Logo.tsx
  frontend/src/components/SignUp/Bubble.tsx
  frontend/src/components/SignUp/SignUpForm.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/SignupPage.tsx
Labels: 프론트엔드

#82 [Fe] Feat: 지도 띄우기
  frontend/public/index.html
  frontend/src/assets/image/iphone.png
  frontend/src/components/Books/BookElements.tsx
  frontend/src/components/common/Modal.tsx
  frontend/src/components/common/NavTemp.tsx
  frontend/src/components/common/Title.tsx
  frontend/src/pages/BooksSearchPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/styles/globalStyles.ts
Labels: 프론트엔드, 기능

#84 [FE] design : 로그인, 회원가입 페이지 레이아웃 오류 수정
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/Login/Logo.tsx
  frontend/src/components/Login/ThirdPartyIcon.tsx
  frontend/src/components/SignUp/SignUpForm.tsx
  frontend/src/components/common/Oauth.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/SignupPage.tsx
Labels: 프론트엔드

#83 [BE] feat: 대여 취소 기능 구현
  backend/src/main/java/com/dongnebook/domain/book/domain/Book.java
  backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
  backend/src/main/java/com/dongnebook/domain/rental/domain/Rental.java
  backend/src/main/java/com/dongnebook/domain/rental/dto/Request/RentalRegisterRequest.java
  backend/src/main/java/com/dongnebook/domain/rental/dto/Response/RentalResponse.java
  backend/src/main/java/com/dongnebook/domain/rental/exception/CanNotRentMyBookException.java
  backend/src/main/java/com/dongnebook/domain/rental/exception/NotCancelableException.java
  backend/src/main/java/com/dongnebook/domain/rental/exception/RentalNotFoundException.java
  backend/src/main/java/com/dongnebook/domain/rental/repository/RentalQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java
  backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
  backend/src/main/resources/application.yml
Labels: 벡엔드, 기능

#81 [BE] Feat : 전체도서목록 무한스크롤 조회 기능 추가
  backend/src/main/java/com/dongnebook/DongnebookApplication.java
  backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
  backend/src/main/java/com/dongnebook/domain/book/domain/Book.java
  backend/src/main/java/com/dongnebook/domain/book/domain/BookState.java
  backend/src/main/java/com/dongnebook/domain/book/dto/Request/BookSearchCondition.java
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookSimpleResponse.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/book/ui/BookController.java
  backend/src/main/java/com/dongnebook/domain/model/Sector.java
  backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
  backend/src/main/java/com/dongnebook/global/dto/request/PageRequest.java
Labels: 벡엔드, 기능

#87 [FE] Design : 지도 검색창 및 현재 위치 버튼 스타일 구현
  frontend/public/index.html
  frontend/src/assets/image/books.png
  frontend/src/assets/image/current.png
  frontend/src/pages/BooksSearchPage.tsx
  frontend/src/pages/LoginPage.tsx
Labels: 프론트엔드

#89 [FE] Feat : 알림 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/NotificationCenter.tsx
  frontend/src/components/common/Toast.tsx
  frontend/src/hooks/README.md
  frontend/src/hooks/useNotify.ts
  frontend/src/index.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/react-app-env.d.ts
  frontend/src/redux/hooks.ts
  frontend/src/redux/slice/README.md
  frontend/src/redux/slice/notificationSlice.tsx
  frontend/src/redux/store.ts
  frontend/src/redux/store.tsx
  frontend/src/utils/README.md
Labels: 프론트엔드, 기능

#86 [BE] Feat: 도서 수령 기능 구현
  backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
  backend/src/main/java/com/dongnebook/domain/rental/domain/Rental.java
  backend/src/main/java/com/dongnebook/domain/rental/exception/CanNotCancelRentalException.java
  backend/src/main/java/com/dongnebook/domain/rental/exception/CanNotReceiveRentalException.java
  backend/src/main/java/com/dongnebook/domain/rental/exception/CanNotReturnRentalException.java
  backend/src/main/java/com/dongnebook/domain/rental/exception/NotReceivableException.java
  backend/src/main/java/com/dongnebook/domain/rental/exception/NotReturnableException.java
  backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java
  backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
Labels: 벡엔드, 기능

#92 [FE] Feat : 주변 상인 마커 및 커스텀 오버레이 구현
  frontend/src/assets/image/books2.png
  frontend/src/assets/image/current2.png
  frontend/src/pages/BooksSearchPage.tsx
Labels: 프론트엔드, 기능

#93 [FE] Feat: 책대여페이지 캘린더 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/test.tsx
  frontend/src/components/Books/BookCalendar.tsx
  frontend/src/pages/BooksCreatePage.tsx
  frontend/src/router/Router.tsx
Labels: 프론트엔드, 기능

#91 [BE] Feat : 찜하기 기능 추가
  backend/src/main/java/com/dongnebook/domain/book/domain/Book.java
  backend/src/main/java/com/dongnebook/domain/dibs/domain/Dibs.java
  backend/src/main/java/com/dongnebook/domain/dibs/exception/DibsNotFoundException.java
  backend/src/main/java/com/dongnebook/domain/dibs/repository/DibsRepository.java
  backend/src/main/java/com/dongnebook/domain/dibs/service/DibsService.java
  backend/src/main/java/com/dongnebook/domain/dibs/ui/DibsController.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
  backend/src/main/java/com/dongnebook/domain/member/dto/request/MemberRegisterRequest.java
  backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
  backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
Labels: 벡엔드, 기능

#90 [BE] Feat : 회원 로그인 기능
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookDetailResponse.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
  backend/src/main/java/com/dongnebook/domain/member/dto/request/MemberLoginRequest.java
  backend/src/main/java/com/dongnebook/domain/member/dto/request/MemberRegisterRequest.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberIdResponse.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberResponse.java
  backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
  backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/SecurityConfiguration.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/SecurityConfigurationV1.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/filter/JwtVerificationFilter.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/handler/MemberAccessDeniedHandler.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/handler/MemberAuthenticationEntryPoint.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/handler/MemberAuthenticationFailureHandler.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/handler/MemberAuthenticationSuccessHandler.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/jwtTokenizer/JwtTokenizer.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/userdetails/CustomUserDetails.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/userdetails/MemberDetailsService.java
  backend/src/main/java/com/dongnebook/global/error/ErrorResponse.java
  backend/src/main/java/com/dongnebook/global/error/exception/BusinessException.java
  backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
  backend/src/main/java/com/dongnebook/global/utils/CustomAuthorityUtils.java
  backend/src/main/resources/application.yml
Labels: 벡엔드, 기능

#94 [FE] Feat : notify, getNotificationPayload util 함수 생성
  frontend/src/components/SignUp/SignUpForm.tsx
  frontend/src/hooks/useNotify.ts
  frontend/src/utils/getNotificationPayload.ts
  frontend/src/utils/notify.ts
Labels: 프론트엔드, 기능

#95 [BE] !HOFIX: 로그인인증인가 - 비밀번호로 로그인 관련 버그
  backend/build.gradle
  backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/dibs/ui/DibsController.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
  backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/SecurityConfiguration.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/filter/ui/MemberController.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/handler/MemberAuthenticationFailureHandler.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/jwtTokenizer/JwtTokenizer.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/userdetails/CustomUserDetails.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/userdetails/MemberDetailsService.java
  backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
  backend/src/main/java/com/dongnebook/global/utils/CustomAuthorityUtils.java
  backend/src/main/resources/application.yml
Labels: 벡엔드, 버그

#96 [FE] Feat: 알림 페이지 구현
  frontend/src/components/LoginOnly/index.tsx
  frontend/src/components/Notice/NoticeIcon.tsx
  frontend/src/components/Notice/NoticeItem.tsx
  frontend/src/pages/NoticePage.tsx
Labels: 프론트엔드, 기능

#98 [FE] Feat: 로딩 애니메이션 구현
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookSectorCountResponse.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/image/lottieloading.json
  frontend/src/components/Loading/Animation.tsx
  frontend/src/components/Loading/index.tsx
  frontend/src/pages/BooksSearchPage.tsx
  frontend/src/router/Router.tsx
Labels: 프론트엔드, 기능

#99 [FE] Refactor : 알림 페이지 props 전달 방식 변경
  frontend/src/components/Notice/NoticeItem.tsx
  frontend/src/pages/NoticePage.tsx
Labels: 프론트엔드, 리팩토링

#105 [FE] Refactor: 코드 분할
  frontend/public/index.html
  frontend/src/components/Map/Map.tsx
  frontend/src/components/Map/Search.tsx
  frontend/src/components/Map/dummy.ts
  frontend/src/pages/BooksSearchPage.tsx
Labels: 프론트엔드, 리팩토링

#106 [FE] Design: 대여내역 레이아웃 수정
  frontend/src/components/History/LendBookLists.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/common/TabLists.tsx
  frontend/src/pages/HistoryPage.tsx
Labels: 프론트엔드

#110 [BE] Refactor: Rental 도메인 토큰값 사용
  backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
  backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
  backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java
Labels: 벡엔드, 리팩토링

#111 [FE] Feat: 검색창 엔터 이벤트, 커스텀 오버레이 클릭 이벤트, 리스트 상태 및 애니메이션 구현, 현재 위치 버튼 기능 구현
  frontend/src/components/Map/Map.tsx
  frontend/src/components/Map/Search.tsx
  frontend/src/components/Map/dummy.ts
  frontend/src/pages/BooksSearchPage.tsx
Labels: 프론트엔드, 기능

#113 [BE] Refactor: 로그인 API Response 내용 수정
  backend/src/main/java/com/dongnebook/global/config/security/auth/filter/JwtAuthenticationFilter.java
Labels: 벡엔드, 리팩토링

#116 [FE] Design: Navbar 컬러 테마속성으로 변경
  frontend/src/components/common/NavTemp.tsx
Labels: 프론트엔드

#114 [BE] Feat : 현재 사용자 불러오는 기능 추가, 검색 기본 페이지용 조회 추가
  backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/repository/MemberQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
Labels: 벡엔드, 리팩토링

#117 [FE] Feat: 책상세조회페이지-상인조회페이지 링크 추가
  frontend/src/pages/BooksDetailPage.tsx
Labels: 프론트엔드, 기능

#118 [FE] feat: 대여기간을 달력에 표시하는 기능을 구현
  frontend/src/components/Books/BookCalendar.tsx
  frontend/src/pages/BooksRentalPage.tsx
  frontend/src/utils/convertDate.ts
Labels: 프론트엔드, 기능

#120 [FE] Feat : API 통신 테스트
  frontend/src/api/test.tsx
  frontend/src/components/Map/BookLists.tsx
  frontend/src/components/Map/Map.tsx
  frontend/src/components/Map/MerchantLists.tsx
  frontend/src/components/Map/dummy.ts
  frontend/src/pages/BooksSearchPage.tsx
Labels: 프론트엔드

#121 [BE] Refactor : 지도 가로세로 1km 로 수정
  backend/src/main/java/com/dongnebook/domain/book/dto/Request/BookSearchCondition.java
  backend/src/main/java/com/dongnebook/domain/model/Location.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/SecurityConfiguration.java
Labels: 벡엔드, 리팩토링

#112 [FE] feat: 회원가입페이지 리팩토링, 아이디, 닉네임 중복 검사 로직 추가
  frontend/src/components/SignUp/IdSection.tsx
  frontend/src/components/SignUp/PasswordSection.tsx
  frontend/src/components/SignUp/SignUpForm.tsx
  frontend/src/constants/README.md
  frontend/src/constants/constants.tsx
Labels: 프론트엔드, 기능, 리팩토링

#125 [FE] Feat: 대여목록 api 호출 구성 및 데이터 바인딩 테스트 완료
  frontend/src/api/history.ts
  frontend/src/components/History/LendBookLists.tsx
  frontend/src/components/History/LendStatusButton.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/History/RentStatusButton.tsx
  frontend/src/components/History/dummy.ts
Labels: 프론트엔드, 기능

#126 [FE] Feat: 로그인 및 로그아웃 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/AuthAPI/api.ts
  frontend/src/api/AuthAPI/index.ts
  frontend/src/components/Books/BookElements.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/LoginOnly/LoginCheckElements.tsx
  frontend/src/components/LoginOnly/index.tsx
  frontend/src/index.tsx
  frontend/src/pages/BooksCreatePage.tsx
  frontend/src/pages/BooksPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/redux/slice/notificationSlice.ts
  frontend/src/redux/slice/userSlice.ts
  frontend/src/redux/store.ts
Labels: 프론트엔드, 기능

#128 [FE] Feat: 지도 검색 - 책 상태 리스트 구현, 커스텀 오버레이 상인 수에 따른 크기 변경, 검색창 로직 추가, 지도 확대 축소 기능 수정
  frontend/src/components/LoginOnly/LoginCheckElements.tsx
  frontend/src/components/Map/BookLists.tsx
  frontend/src/components/Map/Map.tsx
  frontend/src/components/Map/Search.tsx
  frontend/src/components/Map/dummy.ts
  frontend/src/pages/BooksSearchPage.tsx
Labels: 프론트엔드, 기능

#129 [FE] Feat: 회원가입 페이지 상태, hook, util함수 리팩토링
  frontend/src/components/SignUp/IdSection.tsx
  frontend/src/components/SignUp/PasswordSection.tsx
  frontend/src/components/SignUp/SignUpForm.tsx
  frontend/src/hooks/useValidate.ts
  frontend/src/utils/makeSignUpMessages.ts
Labels: 프론트엔드, 리팩토링

#131 [FE] Feat: 지도 검색 주변 도서 대여 상태 표시 , navbar css 수정, 채팅 페이지 서비스 준비중 표시
  frontend/src/components/Map/BookLists.tsx
  frontend/src/components/Map/Map.tsx
  frontend/src/components/Map/MerchantLists.tsx
  frontend/src/components/common/NavTemp.tsx
  frontend/src/pages/ChatsPage.tsx
Labels: 프론트엔드, 기능

#130 [FE] Feat: axios 기본 설정
  frontend/src/api/AuthAPI/api.ts
  frontend/src/api/AuthAPI/index.ts
  frontend/src/api/history.ts
  frontend/src/api/index.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/hooks/useAPI.ts
Labels: 프론트엔드, 리팩토링

#132 [FE] fix: redux store reducer 분리
  frontend/src/components/common/NotificationCenter.tsx
  frontend/src/hooks/useAPI.ts
  frontend/src/redux/store.ts
Labels: 프론트엔드

#123 [BE] Feat: RDS 사용 설정 추가
  backend/build.gradle
  backend/restart-h2.sh
  backend/restart.sh
  backend/src/main/resources/application-rds-createdb.yml
  backend/src/main/resources/application-rds.yml
Labels: 벡엔드, 기능

#133 [BE] Refactor : 주어진 지도 크기에 맞게 응답한다.
  backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
  backend/src/main/java/com/dongnebook/domain/book/dto/Request/BookSearchCondition.java
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookSectorCountResponse.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/book/ui/BookController.java
  backend/src/main/java/com/dongnebook/domain/helloSample/ui/HelloController.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/dto/request/MerchantSearchRequest.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/MerchantSectorCountResponse.java
  backend/src/main/java/com/dongnebook/domain/member/repository/MemberQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
  backend/src/main/java/com/dongnebook/domain/model/Location.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/exception/AccessTokenNotFound.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/filter/JwtVerificationFilter.java
  backend/src/main/java/com/dongnebook/global/dto/response/MultiResponse.java
  backend/src/main/java/com/dongnebook/global/error/ErrorResponse.java
  backend/src/main/java/com/dongnebook/global/error/exception/BusinessException.java
  backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
  backend/src/main/resources/application.yml
Labels: 벡엔드, 리팩토링

#134 [FE] feat: 지도 상인, 책 리스트 검색 구현
  frontend/src/api/test.tsx
  frontend/src/components/Map/BookLists.tsx
  frontend/src/components/Map/Map.tsx
  frontend/src/components/Map/MerchantLists.tsx
  frontend/src/components/Map/Search.tsx
  frontend/src/components/Map/dummy.ts
  frontend/src/pages/BooksSearchPage.tsx
Labels: 프론트엔드, 기능

#127 [BE] Feat : 총갯수 API 응답 수정
  backend/src/main/java/com/dongnebook/domain/book/dto/Request/BookSearchCondition.java
  backend/src/main/java/com/dongnebook/domain/model/Location.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/filter/JwtVerificationFilter.java
Labels: 벡엔드, 리팩토링

#135 [FE] feat: 로그인 관련 성공 및 에러 메시지 구현
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/LoginOnly/index.tsx
  frontend/src/components/common/Input.tsx
  frontend/src/components/common/NavTemp.tsx
  frontend/src/components/common/NotificationCenter.tsx
  frontend/src/hooks/useNotify.ts
Labels: 프론트엔드, 기능

#136 [FE] feat: 회원가입 기능 완성
  frontend/src/components/SignUp/SignUpForm.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/utils/makeSignUpMessages.ts
Labels: 프론트엔드, 기능

#137 [BE] Refactor : 전체조회와 섹터당 리스트 조회 엔드포인트 분리
  backend/src/main/java/com/dongnebook/domain/book/ui/BookController.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberIdResponse.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberLoginResponse.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberResponse.java
  backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/filter/JwtVerificationFilter.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/userdetails/AuthMember.java
Labels: 벡엔드, 리팩토링

#162 Refactor : 로그인 응답에 memberId 추가
  backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
  backend/src/main/java/com/dongnebook/domain/book/dto/Request/BookSearchCondition.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
  backend/src/main/java/com/dongnebook/domain/member/dto/request/MemberEditRequest.java
  backend/src/main/java/com/dongnebook/domain/member/dto/request/MerchantSearchRequest.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/BookDetailMemberResponse.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberDetailResponse.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberLoginResponse.java
  backend/src/main/java/com/dongnebook/domain/member/repository/MemberQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/model/Location.java
Labels: 벡엔드, 리팩토링

#160 [FE] Feat: useGeoLocation, useWindowSize hooks 구현
  frontend/src/api/map.ts
  frontend/src/api/test.tsx
  frontend/src/components/Map/Map.tsx
  frontend/src/components/Map/Search.tsx
  frontend/src/components/common/TabLists.tsx
  frontend/src/hooks/useGeoLocation.ts
  frontend/src/hooks/useWindowSize.ts
  frontend/src/pages/BooksSearchPage.tsx
Labels: 프론트엔드, 기능

#164 [FE] Feat: member axios 파일 생성
  frontend/src/api/history.ts
  frontend/src/api/member.ts
  frontend/src/components/History/LendStatusButton.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/History/RentStatusButton.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/pages/MerchantPage.tsx
Labels: 프론트엔드, 기능

#161 [BE] feat: 빌려준 책 조회 기능 구현
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookInfoResponse.java
  backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
  backend/src/main/java/com/dongnebook/domain/rental/domain/Rental.java
  backend/src/main/java/com/dongnebook/domain/rental/dto/Request/RentalRegisterRequest.java
  backend/src/main/java/com/dongnebook/domain/rental/dto/Response/RentalBookResponse.java
  backend/src/main/java/com/dongnebook/domain/rental/dto/Response/RentalInfoResponse.java
  backend/src/main/java/com/dongnebook/domain/rental/dto/Response/RentalResponse.java
  backend/src/main/java/com/dongnebook/domain/rental/repository/RentalQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/rental/repository/RentalRepository.java
  backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java
Labels: 벡엔드, 기능

#165 [FE] Feat: toast 알림 position 변경
  frontend/src/components/common/NotificationCenter.tsx
  frontend/src/components/common/Toast.tsx
Labels: 프론트엔드, 버그

#167 [FE] Feat: mypage axios 파일 생성
  frontend/src/api/member.ts
  frontend/src/api/mypage.ts
  frontend/src/pages/MerchantPage.tsx
  frontend/src/styles/globalStyles.ts
Labels: 프론트엔드, 기능

#171 [FE] Feat: react-query용 types 디렉토리 생성 및 merchantPage에 react-query 일부 적용
  frontend/src/api/mypage.ts
  frontend/src/components/Map/Search.tsx
  frontend/src/pages/MerchantPage.tsx
  frontend/src/queryType/members.ts
  frontend/src/router/Router.tsx
Labels: 프론트엔드, 기능

#166 [FE] Fix: 회원가입 endpoint 변경, 유효성 검사 에러 수정
  frontend/src/components/SignUp/IdSection.tsx
  frontend/src/components/SignUp/PasswordSection.tsx
  frontend/src/components/SignUp/SignUpForm.tsx
  frontend/src/constants/constants.tsx
  frontend/src/hooks/useValidate.ts
  frontend/src/utils/makeSignUpMessages.ts
Labels: 프론트엔드

#168 [BE] Feat: 빌린 책 조회 기능 구현
  backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
  backend/src/main/java/com/dongnebook/domain/rental/repository/RentalQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/rental/repository/RentalRepository.java
  backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java
Labels: 벡엔드, 기능

#170 [BE] Infra: RDS 연동 설정 변경
  backend/src/main/resources/application-rds.yml
Labels: 벡엔드, 인프라

#173 [FE] feat: 홈화면, 대여목록화면, 개인정보화면 컴포넌트 통합 1차
  frontend/src/api/README.md
  frontend/src/assets/dummy/books.ts
  frontend/src/components/Books/BookItem.tsx
  frontend/src/components/Books/BookItemInfo.tsx
  frontend/src/components/Books/BookItemState.tsx
  frontend/src/components/Books/type.ts
  frontend/src/components/History/LendBookLists.tsx
  frontend/src/components/History/LendBookUserInfo.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/pages/BooksDetailPage.tsx
  frontend/src/pages/BooksPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/redux/slice/userSlice.ts
Labels: 프론트엔드, 리팩토링

#172 [BE] Feat : 지도 섹터 수 변경하는 기능, 사진 업로드 api 추가
  backend/build.gradle
  backend/src/main/java/com/dongnebook/domain/Image/application/AwsS3Service.java
  backend/src/main/java/com/dongnebook/domain/Image/application/ImageUploadService.java
  backend/src/main/java/com/dongnebook/domain/Image/dto/ImageUploadRequest.java
  backend/src/main/java/com/dongnebook/domain/Image/exception/UploadFailed.java
  backend/src/main/java/com/dongnebook/domain/Image/ui/ImageUploadController.java
  backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
  backend/src/main/java/com/dongnebook/domain/book/dto/Request/BookRegisterRequest.java
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookSimpleResponse.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
  backend/src/main/java/com/dongnebook/domain/model/Location.java
  backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
  backend/src/main/resources/application-rds-createdb.yml
  backend/src/main/resources/application-rds.yml
  backend/src/main/resources/application.yml
Labels: 벡엔드, 기능

#174 [FE] Feat: 상인정보 페이지 useQuery 적용
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/history.ts
  frontend/src/api/mypage.ts
  frontend/src/components/Loading/Animation.tsx
  frontend/src/components/Map/Map.tsx
  frontend/src/components/Merchant/BookList.tsx
  frontend/src/components/Merchant/ButtonStatus.tsx
  frontend/src/components/Merchant/Review.tsx
  frontend/src/index.tsx
  frontend/src/pages/Layout.tsx
  frontend/src/pages/LenderInfoPage.tsx
  frontend/src/pages/MerchantPage.tsx
  frontend/src/queryType/members.ts
Labels: 프론트엔드, 기능

#175 [FE] Feat: 마이페이지 작업 및 충돌 해결
  frontend/src/assets/image/dummy2.png
  frontend/src/assets/image/dummy3.png
  frontend/src/components/Books/type.ts
  frontend/src/components/Member/PickBookList.tsx
  frontend/src/components/Member/ReservationBookList.tsx
  frontend/src/pages/ProfilePage.tsx
Labels: 프론트엔드, 기능

#179 [FE] Feat: 대여목록 api 테스트 완료
  frontend/src/api/history.ts
  frontend/src/components/Books/BookItemState.tsx
  frontend/src/components/History/LendBookLists.tsx
  frontend/src/components/History/LendBookUserInfo.tsx
  frontend/src/components/History/LendStatusButton.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/History/RentStatusButton.tsx
  frontend/src/components/History/hooks/useBookReceipt.ts
  frontend/src/components/History/hooks/useBookReturn.ts
  frontend/src/components/History/hooks/useCancelByCustomer.ts
  frontend/src/components/History/hooks/useCancelByMerchant.ts
  frontend/src/components/Merchant/BookList.tsx
  frontend/src/components/Merchant/Review.tsx
Labels: 프론트엔드, 기능

#180 [FE] Feat: 마이페이지 - 프로필, 찜목록 useQuery 적용 및 API 테스트 완료
  frontend/src/api/index.tsx
  frontend/src/api/mypage.ts
  frontend/src/components/Member/PickBookList.tsx
  frontend/src/components/common/BookState/Impossible.tsx
  frontend/src/components/common/BookState/RentalAvailable.tsx
  frontend/src/components/common/BookState/ReservationAvailable.tsx
  frontend/src/hooks/useAPI.ts
  frontend/src/index.tsx
  frontend/src/pages/ProfilePage.tsx
Labels: 프론트엔드, 기능

#183 [BE] Feat :실시간으로알림도착했다고알려주는기능
  backend/src/main/java/com/dongnebook/domain/alarm/domain/AlarmService.java
  backend/src/main/java/com/dongnebook/domain/alarm/domain/EmitterRepository.java
  backend/src/main/java/com/dongnebook/domain/alarm/domain/EmitterRepositoryImpl.java
  backend/src/main/java/com/dongnebook/domain/alarm/ui/AlarmController.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/dibs/service/DibsService.java
  backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
Labels: 벡엔드, 기능

#185 [BE] Feat: 한국시간설정 코드 추가
  backend/src/main/java/com/dongnebook/DongnebookApplication.java
  backend/src/main/java/com/dongnebook/global/HelloController.java
Labels: 벡엔드, 기능

#186 [BE] Feat : 도서정보 검색api 추가
  backend/src/main/java/com/dongnebook/domain/book/dto/KaKaoBookInfoResponse.java
  backend/src/main/java/com/dongnebook/domain/book/ui/BookController.java
Labels: 벡엔드, 기능

#182 [FE] Feat: 알림 페이지에서 아이콘 클릭시 뒤로가기, 새 알림 bgColor설정
  frontend/src/components/Notice/NoticeIcon.tsx
  frontend/src/components/Notice/NoticeItem.tsx
  frontend/src/pages/NoticePage.tsx
  frontend/src/styles/theme.ts
Labels: 프론트엔드, 기능

#190 Feat/be/상세조회 이미지추가
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookResponse.java
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookSimpleResponse.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/book/ui/BookController.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/BookDetailMemberResponse.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberResponse.java
  backend/src/main/java/com/dongnebook/domain/member/repository/MemberQueryRepository.java
Labels: 벡엔드, 기능

#187 [FE] Feat: 마이페이지 - 찜목록 query 구현 완료, 내정보수정하기페이지 및 모달창 css 수정
  frontend/src/api/mypage.ts
  frontend/src/components/Member/BookStatus.tsx
  frontend/src/components/Member/PickBookList.tsx
  frontend/src/components/Merchant/ButtonStatus.tsx
  frontend/src/components/common/Modal.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/ProfilePage.tsx
Labels: 프론트엔드, 기능

#191 [FE] Feat: 대여목록, 상인정보 도서목록 무한스크롤 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/history.ts
  frontend/src/api/mypage.ts
  frontend/src/components/Books/BookItem.tsx
  frontend/src/components/Books/BookItemInfo.tsx
  frontend/src/components/History/LendBookLists.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/History/RentStatusButton.tsx
  frontend/src/components/History/hooks/useBookReceipt.ts
  frontend/src/components/History/hooks/useBookReturn.ts
  frontend/src/components/History/hooks/useCancelByCustomer.ts
  frontend/src/components/History/hooks/useCancelByMerchant.ts
  frontend/src/components/Merchant/BookList.tsx
  frontend/src/components/Merchant/ButtonStatus.tsx
Labels: 프론트엔드, 기능

#192 [FE] Feat: 책전체조회 페이지 조회 및 무한스크롤 구현
  frontend/src/api/books.ts
  frontend/src/api/index.ts
  frontend/src/api/test.tsx
  frontend/src/components/Books/BookDetail.tsx
  frontend/src/components/Books/BookItem.tsx
  frontend/src/components/Books/BookItemInfo.tsx
  frontend/src/components/Books/BookItemState.tsx
  frontend/src/components/History/LendBookLists.tsx
  frontend/src/components/History/LendBookUserInfo.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/pages/BooksDetailPage.tsx
  frontend/src/pages/BooksPage.tsx
Labels: 프론트엔드, 기능

#189 [BE] Infra: EC2 서버 출력 로그 파일화
  backend/restart-h2.sh
  backend/restart.sh
Labels: 벡엔드, 인프라

#194 [BE] Hotfix : 긴급패치
  backend/src/main/java/com/dongnebook/domain/book/dto/Request/BookSearchCondition.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/dto/request/MerchantSearchRequest.java
  backend/src/main/java/com/dongnebook/domain/member/repository/MemberQueryRepository.java
Labels: 벡엔드, 버그

#193 [FE] Feat: 도서상세조회페이지 조회&찜&삭제 구현
  frontend/src/api/books.ts
  frontend/src/components/Books/BookDetail.tsx
  frontend/src/components/Books/BookDetailimage.tsx
  frontend/src/components/Books/BookElements.tsx
  frontend/src/components/Books/BookItemInfo.tsx
  frontend/src/components/Books/type.ts
  frontend/src/pages/BooksDetailPage.tsx
  frontend/src/pages/BooksPage.tsx
  frontend/src/styles/theme.ts
Labels: 프론트엔드, 기능

#195 Hotfix/be/긴급패치
  backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
  backend/src/main/java/com/dongnebook/domain/book/domain/Book.java
  backend/src/main/java/com/dongnebook/domain/book/dto/request/BookRegisterRequest.java
  backend/src/main/java/com/dongnebook/domain/book/dto/request/BookSearchCondition.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/book/ui/BookController.java
Labels: 벡엔드, 버그

#196 [FE] Feat: 책 생성 기능 구현
  frontend/src/components/Books/BookElements.tsx
  frontend/src/components/BooksCreate/Description.tsx
  frontend/src/components/BooksCreate/ModalForTitle.tsx
  frontend/src/components/BooksCreate/Photo.tsx
  frontend/src/components/BooksCreate/RentalFee.tsx
  frontend/src/components/BooksCreate/SearchForm.tsx
  frontend/src/components/BooksCreate/SearchItem.tsx
  frontend/src/components/SignUp/PasswordSection.tsx
  frontend/src/components/common/Modal.tsx
  frontend/src/components/common/NotificationCenter.tsx
  frontend/src/constants/constants.tsx
  frontend/src/pages/BooksCreatePage.tsx
  frontend/src/redux/slice/bookCreateSlice.ts
  frontend/src/redux/store.ts
  frontend/src/styles/theme.ts
Labels: 프론트엔드, 기능, 리팩토링

#197 [FE] Feat: 지도 거의 구현 완료
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/map.ts
  frontend/src/components/Map/BookLists.tsx
  frontend/src/components/Map/CustomOverlay.tsx
  frontend/src/components/Map/Map.tsx
  frontend/src/components/Map/Map2.tsx
  frontend/src/components/Map/MerchantLists.tsx
  frontend/src/components/Map/Search.tsx
  frontend/src/components/Map/dummy.ts
  frontend/src/components/common/NavTemp.tsx
  frontend/src/hooks/useGeoLocation.ts
  frontend/src/hooks/useWindowSize.ts
  frontend/src/pages/BooksSearchPage.tsx
  frontend/tsconfig.json
Labels: 프론트엔드, 기능

#199 [FE] Feat : 마이페이지 예약목록, 내정보수정하기 이미지 등록 및 현재 위치(좌표)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/history.ts
  frontend/src/api/mypage.ts
  frontend/src/components/Member/ReservationBookList.tsx
  frontend/src/components/Member/hooks/useFixInfo.tsx
  frontend/src/components/Member/hooks/useInputImage.tsx
  frontend/src/components/Member/hooks/useInputPlace.tsx
  frontend/src/components/Member/hooks/useInputUsername.tsx
  frontend/src/components/common/Modal.tsx
  frontend/src/hooks/useGeoLocation.ts
  frontend/src/hooks/useGeoLocation2.ts
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/ProfilePage.tsx
Labels: 프론트엔드, 기능

#200 [BE] Feat: 도서 예약하기 기능 구현
  backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
  backend/src/main/java/com/dongnebook/domain/rental/repository/RentalQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java
  backend/src/main/java/com/dongnebook/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/dongnebook/domain/reservation/domain/Reservation.java
  backend/src/main/java/com/dongnebook/domain/reservation/domain/ReservationState.java
  backend/src/main/java/com/dongnebook/domain/reservation/exception/CanNotChangeReservationStateException.java
  backend/src/main/java/com/dongnebook/domain/reservation/exception/CanNotReservationBookStateException.java
  backend/src/main/java/com/dongnebook/domain/reservation/exception/CanNotReservationPersonException.java
  backend/src/main/java/com/dongnebook/domain/reservation/repository/ReservationQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/reservation/repository/ReservationRepository.java
  backend/src/main/java/com/dongnebook/domain/reservation/ui/ReservationsController.java
  backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
Labels: 벡엔드, 기능

#201 [BE] Feat: 도서예약 취소하기 기능 구현
  backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java
  backend/src/main/java/com/dongnebook/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/dongnebook/domain/reservation/domain/Reservation.java
  backend/src/main/java/com/dongnebook/domain/reservation/domain/ReservationState.java
  backend/src/main/java/com/dongnebook/domain/reservation/exception/CanNotChangeReservationStateException.java
  backend/src/main/java/com/dongnebook/domain/reservation/exception/CanNotReservationBookRentalStateException.java
  backend/src/main/java/com/dongnebook/domain/reservation/exception/ReservationNotFoundException.java
  backend/src/main/java/com/dongnebook/domain/reservation/repository/ReservationQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/reservation/ui/ReservationsController.java
  backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
Labels: 벡엔드, 기능

#203 [FE] Feat: 지도에 리액트쿼리 적용
  frontend/src/api/map.ts
  frontend/src/components/Map/BookLists.tsx
  frontend/src/components/Map/CustomOverlay.tsx
  frontend/src/components/Map/CustomOverlayHover.tsx
  frontend/src/components/Map/KakaoMap.tsx
  frontend/src/components/Map/Map.tsx
  frontend/src/components/Map/MerchantLists.tsx
  frontend/src/components/Map/Search.tsx
  frontend/src/hooks/useGeoLocation.ts
  frontend/src/pages/BooksSearchPage.tsx
Labels: 프론트엔드, 기능, 리팩토링

#204 [FE] Feat : 내정보수정하기 페이지
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/mypage.ts
  frontend/src/components/Member/hooks/useFixInfo.tsx
  frontend/src/components/common/Modal.tsx
  frontend/src/pages/ProfileEditPage.tsx
Labels: 프론트엔드, 기능

#205 [BE] Feat: 도서 예약목록 조회 기능 구현
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookSimpleResponse.java
  backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
  backend/src/main/java/com/dongnebook/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/dongnebook/domain/reservation/domain/Reservation.java
  backend/src/main/java/com/dongnebook/domain/reservation/domain/ReservationState.java
  backend/src/main/java/com/dongnebook/domain/reservation/dto/request/ReservationInfoResponse.java
  backend/src/main/java/com/dongnebook/domain/reservation/dto/request/ReservationResponse.java
  backend/src/main/java/com/dongnebook/domain/reservation/exception/CanNotReservationBookStateException.java
  backend/src/main/java/com/dongnebook/domain/reservation/repository/ReservationQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/reservation/ui/ReservationsController.java
Labels: 벡엔드, 기능

#209 [BE] Feat: 채팅기능구현
  backend/build.gradle
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookResponse.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/book/ui/BookController.java
  backend/src/main/java/com/dongnebook/domain/chat/Repository/ChatRepository.java
  backend/src/main/java/com/dongnebook/domain/chat/Repository/RoomRepository.java
  backend/src/main/java/com/dongnebook/domain/chat/application/ChatService.java
  backend/src/main/java/com/dongnebook/domain/chat/application/RoomService.java
  backend/src/main/java/com/dongnebook/domain/chat/domain/ChatMessage.java
  backend/src/main/java/com/dongnebook/domain/chat/domain/ChatRoom.java
  backend/src/main/java/com/dongnebook/domain/chat/domain/RedisChat.java
  backend/src/main/java/com/dongnebook/domain/chat/dto/request/ChatMessageDto.java
  backend/src/main/java/com/dongnebook/domain/chat/dto/request/RoomRequest.java
  backend/src/main/java/com/dongnebook/domain/chat/dto/response/ChatResponse.java
  backend/src/main/java/com/dongnebook/domain/chat/dto/response/LastChatResponse.java
  backend/src/main/java/com/dongnebook/domain/chat/ui/ChatController.java
  backend/src/main/java/com/dongnebook/domain/chat/ui/RedisPublisher.java
  backend/src/main/java/com/dongnebook/domain/chat/ui/RedisSubscriber.java
  backend/src/main/java/com/dongnebook/domain/dibs/repository/DibsRepository.java
  backend/src/main/java/com/dongnebook/domain/dibs/service/DibsService.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
  backend/src/main/java/com/dongnebook/global/config/AmazonS3Config.java
  backend/src/main/java/com/dongnebook/global/config/RedisConfig.java
  backend/src/main/java/com/dongnebook/global/config/WebSocketConfig.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/html.html
Labels: 벡엔드, 기능

#206 [FE] Feat: 책 대여하기 페이지 구현
  frontend/public/index.html
  frontend/src/api/books.ts
  frontend/src/components/Books/BookCalendar.tsx
  frontend/src/components/Books/BookDetail.tsx
  frontend/src/components/Books/BookDetailimage.tsx
  frontend/src/components/Books/BookElements.tsx
  frontend/src/components/Books/BookItemInfo.tsx
  frontend/src/components/History/LendBookUserInfo.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/History/RentStatusButton.tsx
  frontend/src/components/Notice/NoticeIcon.tsx
  frontend/src/pages/BooksBookingPage.tsx
  frontend/src/pages/BooksDetailPage.tsx
  frontend/src/pages/BooksPage.tsx
  frontend/src/pages/BooksRentalPage.tsx
  frontend/src/styles/globalStyles.ts
  frontend/src/utils/calcCalendarDate.ts
  frontend/src/utils/convertDate.ts
Labels: 프론트엔드, 기능

#208 [FE] Refactor: 글 작성 api 통신 react query사용 리팩토링
  frontend/src/api/hooks/useGetBooksByTitle.tsx
  frontend/src/api/hooks/useGetPhotoUrl.tsx
  frontend/src/api/hooks/usePostBooks.tsx
  frontend/src/components/BooksCreate/Description.tsx
  frontend/src/components/BooksCreate/ModalForTitle.tsx
  frontend/src/components/BooksCreate/Photo.tsx
  frontend/src/pages/BooksCreatePage.tsx
  frontend/src/redux/slice/bookCreateSlice.ts
  frontend/src/utils/makeCreateBookMessages.ts
  frontend/src/utils/validateBookCreatePayload.ts
Labels: 프론트엔드, 기능, 리팩토링

#210 [BE] Feat: 리뷰조회 기능 구현
  backend/src/main/java/com/dongnebook/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/dongnebook/domain/reservation/dto/response/ReservationInfoResponse.java
  backend/src/main/java/com/dongnebook/domain/reservation/dto/response/ReservationResponse.java
  backend/src/main/java/com/dongnebook/domain/reservation/repository/ReservationQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/reservation/ui/ReservationsController.java
  backend/src/main/java/com/dongnebook/domain/review/application/ReviewService.java
  backend/src/main/java/com/dongnebook/domain/review/dto/response/ReviewResponse.java
  backend/src/main/java/com/dongnebook/domain/review/repository/ReviewQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/review/ui/ReviewController.java
Labels: 벡엔드, 기능

#213 [BE] refactor : 알림구독할때 토큰 빼기
  backend/src/main/java/com/dongnebook/domain/alarm/domain/EmitterRepositoryImpl.java
  backend/src/main/java/com/dongnebook/domain/alarm/ui/AlarmController.java
Labels: 벡엔드, 리팩토링

#212 [FE] Feat: 미로그인 유저 토스트 알림 및 nav 로그인 추가
  frontend/src/components/Books/BookDetailimage.tsx
  frontend/src/components/Books/BookElements.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/common/NavTemp.tsx
  frontend/src/hooks/useNotify.ts
  frontend/src/pages/BooksDetailPage.tsx
  frontend/src/pages/BooksPage.tsx
Labels: 프론트엔드, 기능

#214 [FE] Feat: 지도 좌표 연동 구현
  frontend/src/api/map.ts
  frontend/src/components/Loading/Animation.tsx
  frontend/src/components/Map/BookLists.tsx
  frontend/src/components/Map/CustomOverlayHover.tsx
  frontend/src/components/Map/KakaoMap.tsx
  frontend/src/components/Map/Search.tsx
  frontend/src/hooks/useGeoLocation.ts
  frontend/src/pages/BooksSearchPage.tsx
Labels: 프론트엔드, 기능

#216 [FE] Feat : 내정보수정하기페이지 - 내 동네 설정 기능 구현 및 geocoder key
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/mypage.ts
  frontend/src/components/Member/hooks/ Avatar.tsx
  frontend/src/components/Member/hooks/useInputImage.tsx
  frontend/src/components/common/Modal.tsx
  frontend/src/hooks/useGeoLocation2.ts
  frontend/src/hooks/useTest
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/ProfilePage.tsx
Labels: 프론트엔드, 기능

#217 [BE] Feat: auth2소셜로그인(회원가입) 기능 구현
  backend/build.gradle
  backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/SecurityConfiguration.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/filter/JwtVerificationFilter.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/oauth/OAuthAttributes.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/oauth/OAuthService.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/oauth/OAuthUserProfile.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/static/application-rds-createdb.yml
  backend/src/main/resources/static/application-rds.yml
Labels: 벡엔드, 기능

#219 [FE] Refactor: api 폴더 구조 적용
  frontend/src/api/createBook.ts
  frontend/src/api/hooks/common/useGetPhotoUrl.tsx
  frontend/src/api/hooks/createBooks/useGetBooksByTitle.tsx
  frontend/src/api/hooks/createBooks/usePostBooks.tsx
  frontend/src/api/hooks/useGetBooksByTitle.tsx
  frontend/src/api/hooks/useGetPhotoUrl.tsx
  frontend/src/components/BooksCreate/ModalForTitle.tsx
  frontend/src/components/BooksCreate/Photo.tsx
  frontend/src/pages/BooksCreatePage.tsx
Labels: 프론트엔드, 리팩토링

#221 [FE] Refactor: api 폴더 구조 적용 및 내정보수정하기 페이지 이미지 등록 수정
  frontend/src/api/hooks/profileedit/Avatar.tsx
  frontend/src/api/hooks/profileedit/useFixInfo.tsx
  frontend/src/components/Member/hooks/useInputPlace.tsx
  frontend/src/components/Member/hooks/useInputUsername.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/utils/validateBookCreatePayload.ts
Labels: 프론트엔드, 기능

#224 [FE] Feat: 지도 무한스크롤 구현
  frontend/src/api/hooks/history/useBookReceipt.ts
  frontend/src/api/hooks/history/useBookReturn.ts
  frontend/src/api/hooks/history/useCancelByCustomer.ts
  frontend/src/api/hooks/history/useCancelByMerchant.ts
  frontend/src/api/hooks/map/useBookList.ts
  frontend/src/api/hooks/map/useBookSector.ts
  frontend/src/api/hooks/map/useMerchantList.ts
  frontend/src/api/hooks/map/useMerchantSector.ts
  frontend/src/api/map.ts
  frontend/src/components/History/LendBookLists.tsx
  frontend/src/components/History/LendStatusButton.tsx
  frontend/src/components/History/RentStatusButton.tsx
  frontend/src/components/Loading/Animation.tsx
  frontend/src/components/Map/BookLists.tsx
  frontend/src/components/Map/CustomOverlay.tsx
  frontend/src/components/Map/KakaoMap.tsx
  frontend/src/components/Map/MerchantLists.tsx
  frontend/src/components/Map/Search.tsx
  frontend/src/hooks/useGeoLocation.ts
  frontend/src/pages/BooksSearchPage.tsx
  frontend/src/redux/slice/geoLocationSlice.ts
  frontend/src/redux/store.ts
  frontend/src/utils/getLocation.ts
  frontend/src/utils/validateBookCreatePayload.ts
Labels: 프론트엔드, 기능

#220 [BE] Refactor: application.yml 위치변경
  backend/src/main/resources/application-rds-createdb.yml
  backend/src/main/resources/application-rds.yml
Labels: 벡엔드, 리팩토링, 인프라

#228 [FE] Feat: 이미지 리사이징 함수 추가, 책 등록시 위치정보 확인 로직 추가
  frontend/src/api/hooks/createBooks/usePostBooks.tsx
  frontend/src/components/BooksCreate/ModalForTitle.tsx
  frontend/src/components/BooksCreate/Photo.tsx
  frontend/src/pages/BooksCreatePage.tsx
  frontend/src/utils/resizeImage.ts
Labels: 프론트엔드, 기능

#230 [FE] Fix: 회원가입 아이디, 닉네임 글자수 제한, 약관 url변경
  frontend/src/components/SignUp/Clause.tsx
  frontend/src/components/SignUp/IdSection.tsx
  frontend/src/components/SignUp/PasswordSection.tsx
  frontend/src/components/SignUp/SignUpForm.tsx
  frontend/src/components/common/Input.tsx
Labels: 프론트엔드, 기능

#231 [FE] Feat: 책 전체조회, 책 상세조회, 대여내역, 찜목록 레이아웃 수정 및 기능구현
  frontend/src/api/books.ts
  frontend/src/api/hooks/history/useBookReceipt.ts
  frontend/src/api/hooks/history/useBookReturn.ts
  frontend/src/api/hooks/history/useCancelByCustomer.ts
  frontend/src/api/hooks/history/useCancelByMerchant.ts
  frontend/src/api/mypage.ts
  frontend/src/components/Books/BookCalendar.tsx
  frontend/src/components/Books/BookDetail.tsx
  frontend/src/components/Books/BookDetailimage.tsx
  frontend/src/components/Books/BookElements.tsx
  frontend/src/components/Books/BookItem.tsx
  frontend/src/components/Books/BookItemInfo.tsx
  frontend/src/components/Books/type.ts
  frontend/src/components/History/LendBookLists.tsx
  frontend/src/components/History/LendStatusButton.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/History/RentStatusButton.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/Member/PickBookList.tsx
  frontend/src/components/Member/ReservationBookList.tsx
  frontend/src/components/common/ScrollToTop.tsx
  frontend/src/pages/BooksBookingPage.tsx
  frontend/src/pages/BooksDetailPage.tsx
  frontend/src/pages/BooksPage.tsx
  frontend/src/pages/BooksRentalPage.tsx
  frontend/src/pages/HistoryPage.tsx
  frontend/src/pages/LayoutTemp.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/ProfilePage.tsx
Labels: 프론트엔드, 기능

#232 [BE] Feat : 액세스토큰 재발급api
  backend/src/main/java/com/dongnebook/domain/alarm/domain/AlarmQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/alarm/domain/AlarmService.java
  backend/src/main/java/com/dongnebook/domain/alarm/exception/AlarmNotFound.java
  backend/src/main/java/com/dongnebook/domain/alarm/ui/AlarmController.java
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookResponse.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
  backend/src/main/java/com/dongnebook/domain/refreshtoken/domain/RefreshToken.java
  backend/src/main/java/com/dongnebook/domain/refreshtoken/exception/TokenEmpty.java
  backend/src/main/java/com/dongnebook/domain/refreshtoken/exception/TokenExpired.java
  backend/src/main/java/com/dongnebook/domain/refreshtoken/exception/TokenInvalid.java
  backend/src/main/java/com/dongnebook/domain/refreshtoken/exception/TokenMalformed.java
  backend/src/main/java/com/dongnebook/domain/refreshtoken/exception/TokenNotFound.java
  backend/src/main/java/com/dongnebook/domain/refreshtoken/exception/TokenSignatureInvalid.java
  backend/src/main/java/com/dongnebook/domain/refreshtoken/exception/TokenUnsupported.java
  backend/src/main/java/com/dongnebook/domain/refreshtoken/repository/RefreshTokenRepository.java
  backend/src/main/java/com/dongnebook/global/config/WebSocketConfig.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/SecurityConfiguration.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/filter/TokenProvider.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/handler/MemberAuthenticationSuccessHandler.java
  backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
  backend/src/main/resources/application-rds-createdb.yml
  backend/src/main/resources/application-rds.yml
Labels: 벡엔드, 기능

#233 [FE] Feat : 마이페이지 반응형 적용, 반응형 컴포넌트 파일 생성
  frontend/src/components/Member/PickBookList.tsx
  frontend/src/components/Member/ReservationBookList.tsx
  frontend/src/components/common/Modal.tsx
  frontend/src/components/common/TabLists.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/ProfilePage.tsx
Labels: 프론트엔드, 기능

#234 [FE] design: 책전체조회페이지 책상태 디자인 수정
  frontend/src/api/books.ts
  frontend/src/components/Books/BookItemState.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/Member/ReservationBookList.tsx
  frontend/src/pages/BooksDetailPage.tsx
  frontend/src/pages/BooksPage.tsx
  frontend/src/pages/ProfilePage.tsx
Labels: 프론트엔드

#235 [FE] Feat : 알림페이지 실시간 알림 SSE 연결, 알림 api 연결
  frontend/src/api/hooks/notice/noticeMessages.ts
  frontend/src/api/hooks/notice/useGetNotice.tsx
  frontend/src/components/LoginOnly/index.tsx
  frontend/src/components/Notice/NoticeIcon.tsx
  frontend/src/components/Notice/NoticeItem.tsx
  frontend/src/pages/NoticePage.tsx
  frontend/src/redux/slice/alarmSlice.ts
  frontend/src/redux/store.ts
  frontend/src/router/Router.tsx
Labels: 프론트엔드, 기능

#236 [BE] Feat : 책 수정 api
  backend/src/main/java/com/dongnebook/domain/alarm/domain/AlarmQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
  backend/src/main/java/com/dongnebook/domain/book/domain/Book.java
  backend/src/main/java/com/dongnebook/domain/book/dto/request/BookEditRequest.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/book/ui/BookController.java
  backend/src/main/java/com/dongnebook/domain/chat/ui/RedisPublisher.java
  backend/src/main/java/com/dongnebook/domain/chat/ui/RedisSubscriber.java
  backend/src/main/java/com/dongnebook/domain/rental/repository/RentalQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/reservation/repository/ReservationQueryRepository.java
  backend/src/main/resources/application-rds-createdb.yml
  backend/src/main/resources/application-rds.yml
  backend/src/main/resources/application.yml
Labels: 벡엔드, 기능

#237 Feat : CORS 설정 추가
  backend/src/main/java/com/dongnebook/global/config/security/auth/SecurityConfiguration.java
Labels: 벡엔드, 기능

#238 [BE] Feat : 대여중인 책이 있을때는 회원정보 수정을 못하게 변경
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
  backend/src/main/java/com/dongnebook/domain/member/repository/MemberQueryRepository.java
  backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
Labels: 벡엔드, 기능

#239 [FE] Fix: 내 동네 설정 location null 해결 및 프로필 아이콘 추가
  frontend/src/components/common/Modal.tsx
  frontend/src/components/common/NavTemp.tsx
  frontend/src/components/common/PcVersion/Header.tsx
  frontend/src/components/common/TabLists.tsx
  frontend/src/hooks/useGeoLocation2.ts
  frontend/src/pages/LayoutTemp.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/redux/slice/reviewCreateSlice.ts
  frontend/src/redux/slice/userInfoSlice.ts
Labels: 프론트엔드, 기능

#241 Refactor : 채팅 내역 볼때 회원 추가
  backend/src/main/java/com/dongnebook/domain/chat/application/ChatService.java
  backend/src/main/java/com/dongnebook/domain/chat/application/RoomService.java
  backend/src/main/java/com/dongnebook/domain/chat/dto/response/ChatResponse.java
  backend/src/main/java/com/dongnebook/domain/chat/dto/response/ChatRoomResponse.java
Labels: 벡엔드, 리팩토링

#244 [BE] Refactor : 채팅 api 회원추가
  backend/src/main/java/com/dongnebook/domain/alarm/domain/AlarmService.java
  backend/src/main/java/com/dongnebook/domain/chat/Repository/ChatRepository.java
  backend/src/main/java/com/dongnebook/domain/chat/application/ChatService.java
  backend/src/main/java/com/dongnebook/domain/chat/application/RoomService.java
  backend/src/main/java/com/dongnebook/domain/chat/domain/ChatMessage.java
  backend/src/main/java/com/dongnebook/domain/chat/domain/RedisChat.java
  backend/src/main/java/com/dongnebook/domain/chat/dto/response/ChatMemberResponse.java
  backend/src/main/java/com/dongnebook/domain/chat/dto/response/ChatRoomResponse.java
  backend/src/main/java/com/dongnebook/domain/chat/ui/ChatController.java
  backend/src/main/java/com/dongnebook/domain/chat/ui/RedisSubscriber.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
Labels: 벡엔드, 기능, 리팩토링

#242 [FE] Remove: NavTemp, LayoutTemp 파일 삭제
  frontend/src/api/auth.ts
  frontend/src/api/hooks/auth/authRenew.ts
  frontend/src/components/Books/BookDetailimage.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/common/Layout.tsx
  frontend/src/components/common/NavBar.tsx
  frontend/src/components/common/NavTemp.tsx
  frontend/src/pages/Layout.tsx
  frontend/src/pages/LayoutTemp.tsx
  frontend/src/redux/slice/userSlice.ts
  frontend/src/router/Router.tsx
Labels: 프론트엔드

#243 [FE] Fix: 실시간 알림 listening 로직 보완, 알림 삭제 구현
  frontend/src/api/hooks/notice/useDeleteNotice.tsx
  frontend/src/components/Notice/NoticeIcon.tsx
  frontend/src/components/Notice/NoticeItem.tsx
  frontend/src/constants/constants.tsx
  frontend/src/redux/slice/alarmSlice.ts
Labels: 프론트엔드, 기능, 리팩토링, 버그

#245 [FE] Feat: 책전체조회,상세조회,예약목록 등
  frontend/src/api/hooks/auth/authRenew.ts
  frontend/src/components/Books/BookDetail.tsx
  frontend/src/components/Books/BookDetailimage.tsx
  frontend/src/components/Books/BookItem.tsx
  frontend/src/components/History/LendBookUserInfo.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/History/SortButton.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/Member/ReservationBookList.tsx
  frontend/src/pages/BooksBookingPage.tsx
  frontend/src/pages/BooksDetailPage.tsx
  frontend/src/pages/BooksPage.tsx
  frontend/src/pages/BooksRentalPage.tsx
  frontend/src/utils/calcCalendarDate.ts
  frontend/src/utils/convertDate.ts
Labels: 프론트엔드

#246 [FE] Design: 회원가입 페이지 반응형 디자인
  frontend/src/components/SignUp/Bubble.tsx
  frontend/src/components/SignUp/Clause.tsx
  frontend/src/components/SignUp/IdSection.tsx
  frontend/src/components/SignUp/PasswordSection.tsx
  frontend/src/components/SignUp/SignUpForm.tsx
  frontend/src/components/common/Input.tsx
  frontend/src/pages/SignupPage.tsx
Labels: 프론트엔드
