Repository codestates-seb/seb40_main_015, pull requests merged in 2022-12, with the labels that each got.

#248 [FE] Design: 책등록 페이지 반응형 디자인, 글쓰기 버튼 클릭시 로직 수정, 대여료 최대 금액 제한
  frontend/src/components/BooksCreate/Description.tsx
  frontend/src/components/BooksCreate/ModalForTitle.tsx
  frontend/src/components/BooksCreate/Photo.tsx
  frontend/src/components/BooksCreate/RentalFee.tsx
  frontend/src/components/BooksCreate/SearchForm.tsx
  frontend/src/pages/BooksCreatePage.tsx
  frontend/src/pages/BooksPage.tsx
  frontend/src/redux/slice/bookCreateSlice.ts
Labels: 프론트엔드, 기능, 버그

#247 [FE] Feat : 마이페이지 오류 해결, 리뷰 페이지 틀, 중복 확인
  frontend/src/components/Member/NicknameSection.tsx
  frontend/src/components/common/Modal.tsx
  frontend/src/components/common/NavTemp.tsx
  frontend/src/pages/LayoutTemp.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/pages/ReviewCreateMessages.tsx
  frontend/src/pages/ReviewCreatePage.tsx
  frontend/src/redux/slice/reviewCreateSlice.ts
Labels: 프론트엔드, 기능

#249 [FE] Design: 로그인 페이지 반응형 디자인
  frontend/src/components/Login/LinkToSignUp.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/Login/Oauth.tsx
  frontend/src/components/common/Title.tsx
  frontend/src/pages/LoginPage.tsx
Labels: 프론트엔드

#250 [FE] Fix: 회원가입 페이지 반응형 비율 조정
  frontend/src/pages/SignupPage.tsx
Labels: 프론트엔드

#251 [FE] Fix : 로그인 성공 이후 회원가입페이지로 이동하는 오류 해결
  frontend/src/components/Books/BookElements.tsx
  frontend/src/components/Member/PickBookList.tsx
  frontend/src/components/Member/ReservationBookList.tsx
  frontend/src/pages/BooksDetailPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/pages/SignupPage.tsx
Labels: 프론트엔드, 버그

#252 [FE] Design : 마이페이지 -> 상인페이지 반응형 디자인
  frontend/src/components/Merchant/BookList.tsx
  frontend/src/components/Merchant/Review.tsx
  frontend/src/pages/MerchantPage.tsx
Labels: 프론트엔드

#254 [FE] Feat : 채팅 기능 구현중
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/chat.ts
  frontend/src/api/hooks/chat/useCreateRoom.ts
  frontend/src/api/hooks/chat/useGetRoomLists.ts
  frontend/src/api/hooks/chat/useGetRoomMessage.ts
  frontend/src/components/Books/BookDetail.tsx
  frontend/src/components/Chat/BookInfo.tsx
  frontend/src/components/Chat/ChatLists.tsx
  frontend/src/components/Chat/Input.tsx
  frontend/src/components/Chat/ReceptionMessage.tsx
  frontend/src/components/Chat/SendingMessage.tsx
  frontend/src/components/common/ScrollBottomButton.tsx
  frontend/src/components/common/Title.tsx
  frontend/src/hooks/useGeoLocation.ts
  frontend/src/pages/ChatRoomPage.tsx
  frontend/src/pages/ChatsPage.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/index.tsx
  frontend/src/router/Router.tsx
  frontend/src/utils/convertDateForChat.ts
  frontend/src/utils/timeForToday.ts
Labels: 프론트엔드, 기능

#253 [BE] Refactor : 채팅방되게 수정, 채팅하면 알람가는 기능 추가
  backend/build.gradle
  backend/src/main/java/com/dongnebook/domain/alarm/domain/AlarmType.java
  backend/src/main/java/com/dongnebook/domain/chat/Repository/ChatRepository.java
  backend/src/main/java/com/dongnebook/domain/chat/application/ChatService.java
  backend/src/main/java/com/dongnebook/domain/chat/application/RoomService.java
  backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/SecurityConfiguration.java
  backend/src/main/resources/application-rds-createdb.yml
  backend/src/main/resources/application-rds.yml
  backend/src/main/resources/application.yml
Labels: 벡엔드, 기능, 리팩토링

#256 [FE] Feat: 지도 레벨 변경
  frontend/src/api/hooks/map/useBookList.ts
  frontend/src/api/hooks/map/useBookSector.ts
  frontend/src/api/hooks/map/useMerchantList.ts
  frontend/src/api/hooks/map/useMerchantSector.ts
  frontend/src/components/Loading/Animation.tsx
  frontend/src/components/Map/BookLists.tsx
  frontend/src/components/Map/KakaoMap.tsx
  frontend/src/components/common/Layout.tsx
  frontend/src/pages/ProfilePage.tsx
Labels: 프론트엔드, 기능

#255 [FE] Fix: 마이페이지 - 예약목록 CSS 수정
  frontend/src/api/mypage.ts
  frontend/src/components/Member/ReservationBookList.tsx
  frontend/src/pages/ProfilePage.tsx
Labels: 프론트엔드

#257 [BE] Refactor : RedisChat LocalDateTime 역직렬화 문제 해결
  backend/build.gradle
  backend/src/main/java/com/dongnebook/domain/chat/domain/RedisChat.java
Labels: 벡엔드, 기능, 리팩토링

#258 [FE] Design: 알림아이콘 위치 조정, 알림 삭제시 리프레쉬
  frontend/src/components/Notice/NoticeIcon.tsx
  frontend/src/components/Notice/NoticeItem.tsx
Labels: 프론트엔드, 버그

#259 [FE] Design: 글 작성 페이지 컴포넌트 배경색 흰색 적용
  frontend/src/components/BooksCreate/SearchForm.tsx
  frontend/src/pages/BooksCreatePage.tsx
Labels: 프론트엔드

#260 [FE] Design: 회원가입, 로그인 페이지 Input 위치조정, 컴포넌트 배경색 설정
  frontend/src/components/common/Input.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/SignupPage.tsx
Labels: 프론트엔드

#262 [FE] Fix: 전체조회/상세조회/대여및예약 스타일 수정
  frontend/src/api/hooks/auth/authRenew.ts
  frontend/src/components/Books/BookCalendar.tsx
  frontend/src/components/Books/BookDetail.tsx
  frontend/src/components/Books/BookDetailimage.tsx
  frontend/src/components/Books/BookElements.tsx
  frontend/src/components/Books/BookItem.tsx
  frontend/src/components/Books/BookItemInfo.tsx
  frontend/src/components/History/LendBookLists.tsx
  frontend/src/components/History/LendStatusButton.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/pages/BooksBookingPage.tsx
  frontend/src/pages/BooksDetailPage.tsx
  frontend/src/pages/BooksPage.tsx
  frontend/src/pages/BooksRentalPage.tsx
Labels: 프론트엔드

#261 [FE] Fix : 마이페이지 반응형 및 CSS 수정
  frontend/src/api/mypage.ts
  frontend/src/components/Member/ReservationBookList.tsx
  frontend/src/components/common/NavBar.tsx
  frontend/src/pages/BooksPage.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/ProfilePage.tsx
Labels: 프론트엔드

#264 [FE] Feat: 채팅 구현 및 지도 반응형
  frontend/src/api/hooks/chat/useGetRoomMessage.ts
  frontend/src/api/hooks/map/useBookList.ts
  frontend/src/api/hooks/map/useBookSector.ts
  frontend/src/api/hooks/map/useMerchantList.ts
  frontend/src/api/hooks/map/useMerchantSector.ts
  frontend/src/components/Books/BookDetail.tsx
  frontend/src/components/Chat/BookInfo.tsx
  frontend/src/components/Chat/Input.tsx
  frontend/src/components/Map/KakaoMap.tsx
  frontend/src/components/Map/MerchantLists.tsx
  frontend/src/components/common/Layout.tsx
  frontend/src/components/common/ScrollBottomButton.tsx
  frontend/src/pages/BooksSearchPage.tsx
  frontend/src/pages/ChatRoomPage.tsx
  frontend/src/utils/scrollToBottom.ts
Labels: 프론트엔드, 기능

#266 [BE] Refactor : 채팅방 최신순으로 오게 변경, 채팅방 목록에서 회원은 항상 상대방으로
  backend/build.gradle
  backend/src/main/java/com/dongnebook/domain/chat/Repository/ChatRepository.java
  backend/src/main/java/com/dongnebook/domain/chat/domain/ChatRoom.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/filter/TokenProvider.java
  backend/src/main/resources/application-rds-createdb.yml
  backend/src/main/resources/application-rds.yml
  backend/src/main/resources/application.yml
Labels: 벡엔드, 리팩토링

#268 [FE] Feat: 상하단 타이틀/헤더/네브바에 애니메이션 추가
  frontend/src/api/hooks/auth/authRenew.ts
  frontend/src/components/Books/BookElements.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/common/NavBar.tsx
  frontend/src/components/common/PcVersion/Header/Header.tsx
  frontend/src/components/common/Title.tsx
  frontend/src/pages/BooksPage.tsx
  frontend/src/styles/globalStyles.ts
Labels: 프론트엔드

#267 [FE] Feat: 새로운 채팅 수신시 알림 처리 설정
  frontend/src/api/hooks/notice/noticeMessages.ts
  frontend/src/components/Notice/NoticeItem.tsx
Labels: 프론트엔드, 기능

#270 [FE] Design: 반응형 토스트 알림 설정
  frontend/src/components/common/NotificationCenter.tsx
  frontend/src/components/common/Toast.tsx
Labels: 프론트엔드

#271 [FE] Design: header 반응형 설정, 로그인 체크 로직 추가
  frontend/src/components/BooksCreate/ModalForTitle.tsx
  frontend/src/components/common/PcVersion/Header/Header.tsx
  frontend/src/components/common/PcVersion/Header/Logo.tsx
  frontend/src/components/common/Title.tsx
Labels: 프론트엔드

#272 [FE] !HOTFIX: 로그인 알림 에러 수정
  frontend/src/components/common/PcVersion/Header/Header.tsx
Labels: 프론트엔드, 버그

#277 [BE] Refactor: 리뷰 상인 평균평점 반영 로직 추가
  backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/BookDetailMemberResponse.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberDetailResponse.java
  backend/src/main/java/com/dongnebook/domain/review/application/ReviewService.java
Labels: 벡엔드, 기능, 리팩토링

#276 [FE] Design: 채팅, 지도 반응형
  frontend/src/components/Books/BookDetail.tsx
  frontend/src/components/Chat/BookInfo.tsx
  frontend/src/components/Chat/Input.tsx
  frontend/src/components/Chat/ReceptionMessage.tsx
  frontend/src/components/Chat/SendingMessage.tsx
  frontend/src/components/Map/KakaoMap.tsx
  frontend/src/components/Merchant/BookList.tsx
  frontend/src/components/common/Layout.tsx
  frontend/src/hooks/useGeoLocation.ts
  frontend/src/pages/BooksSearchPage.tsx
  frontend/src/pages/ChatRoomPage.tsx
  frontend/src/pages/ChatsPage.tsx
  frontend/src/pages/MerchantPage.tsx
Labels: 프론트엔드

#278 [FE] fix: 무한스크롤 엘리먼트, 찜하기, 예약취소, 책상세조회
  frontend/public/index.html
  frontend/src/api/hooks/auth/authRenew.ts
  frontend/src/api/mypage.ts
  frontend/src/components/Books/BookDetail.tsx
  frontend/src/components/Books/BookDetailimage.tsx
  frontend/src/components/History/LendBookLists.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/Member/PickBookList.tsx
  frontend/src/components/Member/ReservationBookList.tsx
  frontend/src/pages/BooksDetailPage.tsx
  frontend/src/pages/BooksPage.tsx
Labels: 프론트엔드, 기능

#284 [FE] Feat: 데스크탑 notice 아이콘 위치 조정, 윈도우 환경에서 알림 삭제시 새로고침
  frontend/src/components/Notice/NoticeIcon.tsx
  frontend/src/components/Notice/NoticeItem.tsx
Labels: 프론트엔드, 기능

#279 [FE] Feat: 데스크탑버전 aside 추가
  frontend/src/assets/image/repository.png
  frontend/src/components/common/Layout.tsx
  frontend/src/components/common/PcVersion/Asides/MemberCard.tsx
  frontend/src/components/common/PcVersion/Asides/Repository.tsx
  frontend/src/components/common/PcVersion/Asides/TeamMember.tsx
  frontend/src/components/common/PcVersion/Asides/memberInfo.ts
  frontend/src/components/common/PcVersion/Repository.tsx
  frontend/src/components/common/PcVersion/TeamMember.tsx
Labels: 프론트엔드, 기능

#281 [FE] Feat: 로그인, 회원가입 화면 header 추가, 로그인 여부에 따라 텍스트 수정
  frontend/src/components/Login/Logo.tsx
  frontend/src/components/common/PcVersion/Header/Header.tsx
  frontend/src/components/common/PcVersion/Header/Logo.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/SignupPage.tsx
Labels: 프론트엔드, 기능

#282 [FE] Design: LoginCheckElement 반응형, 컴포넌트 배경색 적용
  frontend/src/components/LoginOnly/LoginCheckElements.tsx
Labels: 프론트엔드

#286 [FE] Design : pc version hero image 작업
  frontend/src/assets/image/pc1.png
  frontend/src/assets/image/pc2.png
  frontend/src/assets/image/pc3.png
  frontend/src/assets/image/pc4.png
  frontend/src/assets/image/pc5.png
  frontend/src/assets/image/pc6.png
  frontend/src/assets/image/pc7.png
  frontend/src/pages/MainPage.tsx
Labels: 프론트엔드

#287 [FE] feat: 액세스토큰, 마이페이지, 회원가입, 책상세조회페이지
  frontend/src/api/hooks/auth/authRenew.ts
  frontend/src/components/Books/BookDetail.tsx
  frontend/src/components/Books/type.ts
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/Member/PickBookList.tsx
  frontend/src/components/Member/ReservationBookList.tsx
  frontend/src/components/common/Layout.tsx
  frontend/src/pages/BooksDetailPage.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/SignupPage.tsx
Labels: 프론트엔드

#285 [BE] Refactor : 쿠키 기본값 변경, 채팅방 api 변경
  backend/build.gradle
  backend/src/main/java/com/dongnebook/domain/book/domain/Book.java
  backend/src/main/java/com/dongnebook/domain/chat/dto/response/LastChatResponse.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
  backend/src/main/java/com/dongnebook/domain/member/dto/request/MemberEditRequest.java
  backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
  backend/src/main/java/com/dongnebook/domain/review/application/ReviewService.java
  backend/src/main/java/com/dongnebook/global/HelloController.java
  backend/src/main/java/com/dongnebook/global/config/Py6spyConfig.java
  backend/src/main/java/com/dongnebook/global/config/security/auth/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/dongnebook/global/test/HelloController.java
  backend/src/main/resources/application-rds-createdb.yml
  backend/src/main/resources/application-rds.yml
  backend/src/main/resources/application.yml
Labels: 벡엔드, 기능, 리팩토링

#288 [FE] Feat : 메인 페이지 hero section 구성 및 라우터 수정
  frontend/src/assets/image/mo1.png
  frontend/src/assets/image/mo2.png
  frontend/src/assets/image/mo3.png
  frontend/src/assets/image/mo4.png
  frontend/src/assets/image/mo5.png
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/router/Router.tsx
Labels: 프론트엔드

#289 [FE] design: 상인페이지 / 책상세조회 / 대여및예약 스타일 수정
  frontend/src/api/hooks/auth/authRenew.ts
  frontend/src/components/Books/BookDetail.tsx
  frontend/src/components/Books/BookDetailimage.tsx
  frontend/src/components/Books/BookElements.tsx
  frontend/src/components/Books/BookItemState.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/Member/PickBookList.tsx
  frontend/src/components/Member/ReservationBookList.tsx
  frontend/src/components/Merchant/BookList.tsx
  frontend/src/components/common/Layout.tsx
  frontend/src/pages/BooksBookingPage.tsx
  frontend/src/pages/BooksRentalPage.tsx
  frontend/src/pages/MerchantPage.tsx
Labels: 프론트엔드

#291 [FE] Design : mobile hero section 구성
  frontend/src/assets/image/mo1.png
  frontend/src/assets/image/mo2.png
  frontend/src/assets/image/mo3.png
  frontend/src/assets/image/mo4.png
  frontend/src/assets/image/mo5.png
  frontend/src/pages/MainPage.tsx
  frontend/src/router/Router.tsx
Labels: 프론트엔드

#292 [FE] Feat: 지도, 채팅 기능 추가 및 디자인 수정
  frontend/public/index.html
  frontend/src/api/hooks/map/useBookList.ts
  frontend/src/api/hooks/map/useBookSector.ts
  frontend/src/api/hooks/map/useMerchantList.ts
  frontend/src/api/hooks/map/useMerchantSector.ts
  frontend/src/components/Chat/BookInfo.tsx
  frontend/src/components/Chat/ChatLists.tsx
  frontend/src/components/Chat/ReceptionMessage.tsx
  frontend/src/components/Chat/SendingMessage.tsx
  frontend/src/components/History/LendBookUserInfo.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/common/ScrollBottomButton.tsx
  frontend/src/pages/ChatRoomPage.tsx
  frontend/src/pages/ChatsPage.tsx
  frontend/src/utils/convertDateForChat.ts
Labels: 프론트엔드, 기능

#293 [BE] Feat: 대여목록(빌린책, 빌려준책) 조회시, 필터링 기능 추가
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookInfoResponse.java
  backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
  backend/src/main/java/com/dongnebook/domain/rental/dto/request/RentalSearchCondition.java
  backend/src/main/java/com/dongnebook/domain/rental/dto/response/RentalBookResponse.java
  backend/src/main/java/com/dongnebook/domain/rental/dto/response/RentalInfoResponse.java
  backend/src/main/java/com/dongnebook/domain/rental/repository/RentalQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java
  backend/src/main/java/com/dongnebook/global/utils/Enum.java
  backend/src/main/java/com/dongnebook/global/utils/EnumValidator.java
Labels: 벡엔드, 기능, 리팩토링

#294 [FE] feat: 액세스토큰 갱신 로직 추가
  frontend/src/hooks/useAPI.ts
Labels: 프론트엔드, 기능

#295 [FE] Feat : mobile hero section - carousel 완성
  frontend/src/components/HeroSection/MobileHeroSection.tsx
  frontend/src/pages/MainPage.tsx
Labels: 프론트엔드

#296 [FE] Feat: 채팅 로직 리팩토링
  frontend/src/api/hooks/chat/useGetRoomMessage.ts
  frontend/src/components/Chat/ChatLists.tsx
  frontend/src/pages/ChatRoomPage.tsx
Labels: 프론트엔드, 기능, 리팩토링

#297 [FE] Feat: 데스크탑 히어로섹션 작업중
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/image/pc1.png
  frontend/src/assets/image/pc2.png
  frontend/src/assets/image/pc3.png
  frontend/src/assets/image/pc4.png
  frontend/src/assets/image/pc5.png
  frontend/src/assets/image/pc6.png
  frontend/src/assets/image/pc7.png
  frontend/src/components/HeroSection/HeroSectionDeskTop.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/styles/globalStyles.ts
Labels: 프론트엔드

#298 [FE] Feat: 아이디 중복검사 api path 수정
  frontend/src/components/SignUp/IdSection.tsx
Labels: 프론트엔드

#300 [FE] Feat: 랜딩 페이지 완성
  frontend/src/components/HeroSection/HeroSectionDeskTop.tsx
  frontend/src/components/HeroSection/MobileHeroSection.tsx
  frontend/src/components/Notice/NoticeIcon.tsx
  frontend/src/pages/MainPage.tsx
Labels: 프론트엔드

#299 [FE] Feat: 카카오톡 오픈 그래프 적용
  frontend/public/index.html
  frontend/src/components/HeroSection/MobileHeroSection.tsx
  frontend/src/pages/MainPage.tsx
Labels: 프론트엔드

#302 [FE] Feat: pwa 설정
  frontend/package-lock.json
  frontend/package.json
  frontend/public/icons/apple-touch-icon-114x114.png
  frontend/public/icons/apple-touch-icon-120x120.png
  frontend/public/icons/apple-touch-icon-144x144.png
  frontend/public/icons/apple-touch-icon-152x152.png
  frontend/public/icons/apple-touch-icon-57x57.png
  frontend/public/icons/apple-touch-icon-60x60.png
  frontend/public/icons/apple-touch-icon-72x72.png
  frontend/public/icons/apple-touch-icon-76x76.png
  frontend/public/icons/favicon-128.png
  frontend/public/icons/favicon-16x16.png
  frontend/public/icons/favicon-196x196.png
  frontend/public/icons/favicon-32x32.png
  frontend/public/icons/favicon-96x96.png
  frontend/public/icons/favicon.ico
  frontend/public/icons/mstile-144x144.png
  frontend/public/icons/mstile-150x150.png
  frontend/public/icons/mstile-310x150.png
  frontend/public/icons/mstile-310x310.png
  frontend/public/icons/mstile-70x70.png
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/api/hooks/map/useBookSector.ts
  frontend/src/components/History/LendBookUserInfo.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/index.tsx
  frontend/src/service-worker.ts
  frontend/src/serviceWorkerRegistration.ts
Labels: 프론트엔드, 기능

#303 [FE] Comment: 미사용 컴포넌트 임시 주석처리
  frontend/src/components/HeroSection/MobileHeroSection.tsx
  frontend/src/pages/HistoryPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/ReviewCreatePage.tsx
  frontend/src/pages/SignupPage.tsx
Labels: 프론트엔드

#304 [FE] Feat: pwa 모바일 아이콘 추가
  frontend/public/icons/apple-touch-icon-192x192.png
  frontend/public/icons/favicon-512x512.png
  frontend/public/index.html
  frontend/public/manifest.json
Labels: 프론트엔드

#305 [FE] Feat: mobile hero section 버튼 위치 조정, 뒤로가기 버튼 추가
  frontend/src/components/HeroSection/MobileHeroSection.tsx
  frontend/src/components/common/Title.tsx
Labels: 프론트엔드, 기능

#310 [FE] Feat : 지도, 채팅 수정
  frontend/src/api/hooks/chat/useGetRoomLists.ts
  frontend/src/api/hooks/map/useBookSector.ts
  frontend/src/api/hooks/map/useMerchantSector.ts
  frontend/src/components/Map/CustomOverlay.tsx
  frontend/src/components/Map/KakaoMap.tsx
  frontend/src/components/Member/PickBookList.tsx
  frontend/src/components/Merchant/BookList.tsx
  frontend/src/components/Merchant/ButtonStatus.tsx
  frontend/src/pages/ChatsPage.tsx
Labels: 프론트엔드, 기능

#311 [FE] Feat : 알림 없을때 메시지 설정
  frontend/src/components/Notice/NoticeItem.tsx
Labels: 프론트엔드

#313 [FE] Fix: 코드 정리
  frontend/src/api/mypage.ts
  frontend/src/components/HeroSection/MobileHeroSection.tsx
  frontend/src/components/common/Modal.tsx
  frontend/src/hooks/useGeoLocation2.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/ProfilePage.tsx
Labels: 프론트엔드

#314 [FE] Feat: pwa
  frontend/public/icons/apple-touch-icon-114x114.png
  frontend/public/icons/apple-touch-icon-120x120.png
  frontend/public/icons/apple-touch-icon-144x144.png
  frontend/public/icons/apple-touch-icon-152x152.png
  frontend/public/icons/apple-touch-icon-57x57.png
  frontend/public/icons/apple-touch-icon-60x60.png
  frontend/public/icons/apple-touch-icon-72x72.png
  frontend/public/icons/apple-touch-icon-76x76.png
  frontend/public/icons/favicon-128x128.png
  frontend/public/icons/favicon-16x16.png
  frontend/public/icons/mstile-144x144.png
  frontend/public/icons/mstile-150x150.png
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/components/Merchant/ButtonStatus.tsx
  frontend/src/pages/ChatRoomPage.tsx
Labels: 프론트엔드, 기능

#316 [BE] Refactor: build 오류 test 제거
  backend/src/test/java/com/dongnebook/DongnebookApplicationTests.java
  backend/src/test/java/com/dongnebook/domain/rental/application/RentalServiceTest.java
Labels: 벡엔드, 리팩토링

#318 [FE] Feat: pwa
  frontend/public/manifest.json
Labels: 프론트엔드

#324 [FE] Design: 스크롤바 제거
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/src/styles/globalStyles.ts
  frontend/src/styles/theme.ts
Labels: 프론트엔드

#325 [FE] Design : 마이페이지 버튼 통일
  frontend/src/components/Member/PickBookList.tsx
  frontend/src/components/Merchant/ButtonStatus.tsx
Labels: 프론트엔드

#326 [FE] Design: aside qr코드 추가
  frontend/src/assets/image/qr.png
  frontend/src/assets/image/repository.png
  frontend/src/components/common/PcVersion/Asides/Repository.tsx
  frontend/src/components/common/PcVersion/Asides/TeamMember.tsx
Labels: 프론트엔드

#328 [FE] Feat: 지도 및 채팅 수정
  frontend/public/manifest.json
  frontend/src/api/hooks/chat/useGetRoomLists.ts
  frontend/src/api/hooks/chat/useGetRoomMessage.ts
  frontend/src/api/hooks/history/useLendBookLists.ts
  frontend/src/api/hooks/history/useRentalBookLists.ts
  frontend/src/api/hooks/map/useBookList.ts
  frontend/src/api/hooks/map/useBookSector.ts
  frontend/src/api/hooks/map/useMerchantList.ts
  frontend/src/api/hooks/map/useMerchantSector.ts
  frontend/src/api/hooks/merchant/useMerchantBookList.ts
  frontend/src/api/hooks/user/useUserInfo.ts
  frontend/src/api/mypage.ts
  frontend/src/components/Books/BookDetail.tsx
  frontend/src/components/Chat/ChatLists.tsx
  frontend/src/components/Chat/Input.tsx
  frontend/src/components/Chat/ReceptionMessage.tsx
  frontend/src/components/Chat/SendingMessage.tsx
  frontend/src/components/History/LendBookLists.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/Map/KakaoMap.tsx
  frontend/src/components/Merchant/BookList.tsx
  frontend/src/components/Merchant/ButtonStatus.tsx
  frontend/src/components/common/ScrollBottomButton.tsx
  frontend/src/hooks/useTest
  frontend/src/hooks/useWindowSize.ts
  frontend/src/pages/ChatRoomPage.tsx
  frontend/src/pages/ChatsPage.tsx
  frontend/src/pages/MerchantPage.tsx
Labels: 프론트엔드, 기능, 리팩토링

#331 [BE] Feat : 알람 전체 삭제 기능, 반납 대여 알림
  backend/src/main/java/com/dongnebook/DongnebookApplication.java
  backend/src/main/java/com/dongnebook/domain/alarm/domain/AlarmQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/alarm/domain/AlarmService.java
  backend/src/main/java/com/dongnebook/domain/alarm/ui/AlarmController.java
  backend/src/main/java/com/dongnebook/domain/chat/domain/ChatRoom.java
  backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
  backend/src/main/java/com/dongnebook/domain/rental/repository/RentalQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java
  backend/src/main/resources/application-rds-createdb.yml
  backend/src/main/resources/application-rds.yml
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/dongnebook/domain/rental/application/RentalServiceTest.java
Labels: 벡엔드, 기능

#332 [BE] Infra: 특정IP를 바라보도록 변경
  backend/src/main/resources/application-rds-createdb.yml
  backend/src/main/resources/application-rds.yml
Labels: 벡엔드, 인프라

#333 [FE] Refactor: 쿼리 로직 분리 / 로그아웃추가
  frontend/src/api/auth.ts
  frontend/src/api/hooks/auth/useAuthRenew.ts
  frontend/src/api/hooks/books/useDeleteReserv.ts
  frontend/src/api/hooks/books/useGetBookDetail.ts
  frontend/src/api/hooks/books/useGetBooksList.ts
  frontend/src/api/hooks/books/usePostBookBooking.ts
  frontend/src/api/hooks/books/usePostBookRental.ts
  frontend/src/api/hooks/member/useFixInfo.tsx
  frontend/src/api/hooks/member/useGetAddress.ts
  frontend/src/api/hooks/member/useGetPickList.ts
  frontend/src/api/hooks/member/useGetReservList.ts
  frontend/src/components/History/RentStatusButton.tsx
  frontend/src/components/Member/Avatar.tsx
  frontend/src/components/Member/PickBookList.tsx
  frontend/src/components/Member/ReservationBookList.tsx
  frontend/src/components/common/Layout.tsx
  frontend/src/pages/BooksBookingPage.tsx
  frontend/src/pages/BooksDetailPage.tsx
  frontend/src/pages/BooksPage.tsx
  frontend/src/pages/BooksRentalPage.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/ProfilePage.tsx
Labels: 프론트엔드, 리팩토링

#337 [BE] Infra: github action 자동배포 설정
  .github/workflows/gradle.yml
  appspec.yml
  backend/src/main/resources/application-API-KEY.yml
  backend/src/main/resources/application-rds-createdb.yml
  backend/src/main/resources/application-rds.yml
  backend/src/main/resources/application.yml
  scripts/deploy.sh
Labels: 벡엔드, 인프라

#338 [FE] Feat: 채팅방 프로필 이미지 클릭시 상세페이지 이동
  frontend/src/components/Books/BookDetail.tsx
  frontend/src/components/Chat/ReceptionMessage.tsx
  frontend/src/components/Chat/SendingMessage.tsx
  frontend/src/hooks/useGeoLocation.ts
  frontend/src/pages/ChatRoomPage.tsx
Labels: 프론트엔드, 기능

#339 [FE] Refactor: 타입 지정 및 컴포넌트 분리
  frontend/src/api/hooks/map/useBookList.ts
  frontend/src/api/hooks/map/useBookSector.ts
  frontend/src/api/hooks/map/useMerchantList.ts
  frontend/src/api/hooks/map/useMerchantSector.ts
  frontend/src/components/Chat/ChatLists.tsx
  frontend/src/components/Chat/MessageList.tsx
  frontend/src/components/Chat/SendingMessage.tsx
  frontend/src/components/History/LendBookLists.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/History/RentStatusButton.tsx
  frontend/src/components/Map/BookLists.tsx
  frontend/src/components/Map/CustomOverlay.tsx
  frontend/src/components/Map/CustomOverlayHover.tsx
  frontend/src/components/Map/KaKaoMapTypes.ts
  frontend/src/components/Map/KakaoMap.tsx
  frontend/src/components/Map/MerchantLists.tsx
  frontend/src/components/Map/Search.tsx
  frontend/src/hooks/useGeoLocation.ts
  frontend/src/pages/BooksSearchPage.tsx
  frontend/src/pages/ChatRoomPage.tsx
  frontend/src/pages/ChatsPage.tsx
Labels: 프론트엔드, 리팩토링

#341 [FE] Refactor: 지도 레벨 8까지 지원 및 타입 지정
  frontend/src/api/history.ts
  frontend/src/api/hooks/history/useBookReceipt.ts
  frontend/src/api/hooks/history/useBookReturn.ts
  frontend/src/api/hooks/history/useCancelByCustomer.ts
  frontend/src/api/hooks/history/useCancelByMerchant.ts
  frontend/src/api/hooks/map/useBookList.ts
  frontend/src/api/hooks/map/useBookSector.ts
  frontend/src/api/hooks/map/useMerchantList.ts
  frontend/src/api/hooks/map/useMerchantSector.ts
  frontend/src/components/Books/BookItem.tsx
  frontend/src/components/Books/BookItemInfo.tsx
  frontend/src/components/Books/type.ts
  frontend/src/components/History/LendBookLists.tsx
  frontend/src/components/History/LendBookUserInfo.tsx
  frontend/src/components/History/LendStatusButton.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/History/RentStatusButton.tsx
  frontend/src/components/History/types.ts
  frontend/src/components/Map/CustomOverlay.tsx
  frontend/src/components/Map/KakaoMap.tsx
  frontend/src/hooks/useGeoLocation.ts
  frontend/src/hooks/useWindowSize.ts
  frontend/src/pages/BooksSearchPage.tsx
  frontend/src/pages/HistoryPage.tsx
  frontend/src/pages/ProfilePage.tsx
Labels: 프론트엔드, 리팩토링

#342 [FE] Feat: 리뷰등록 구현
  frontend/src/api/hooks/review/useCreateReview.tsx
  frontend/src/api/hooks/review/useReviewList.tsx
  frontend/src/api/review.ts
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/History/RentStatusButton.tsx
  frontend/src/components/Merchant/Review.tsx
  frontend/src/components/Merchant/ReviewList.tsx
  frontend/src/components/Review/Review.tsx
  frontend/src/components/common/ConfirmModal.tsx
  frontend/src/pages/MerchantPage.tsx
  frontend/src/pages/ReviewCreatePage.tsx
  frontend/src/styles/globalStyles.ts
Labels: 프론트엔드, 기능

#344 [FE] Refactor: 리팩토링, 미사용 import, 주석 등 제거
  frontend/src/api/hooks/notice/noticeMessages.ts
  frontend/src/components/BooksCreate/Description.tsx
  frontend/src/components/BooksCreate/Photo.tsx
  frontend/src/components/HeroSection/HeroSectionDeskTop.tsx
  frontend/src/components/HeroSection/heroSlides.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/Login/ThirdPartyIcon.tsx
  frontend/src/components/Notice/NoticeIcon.tsx
  frontend/src/components/Notice/NoticeItem.tsx
  frontend/src/components/SignUp/Bubble.tsx
  frontend/src/components/SignUp/Clause.tsx
  frontend/src/components/SignUp/IdSection.tsx
  frontend/src/components/SignUp/PasswordSection.tsx
  frontend/src/components/common/Input.tsx
  frontend/src/components/common/LinkToSign.tsx
  frontend/src/components/common/NotificationCenter.tsx
  frontend/src/components/common/PcVersion/Header/Header.tsx
  frontend/src/components/common/PcVersion/Header/headerInfo.ts
  frontend/src/components/common/Toast.tsx
  frontend/src/constants/constants.tsx
  frontend/src/constants/noticeMessages.ts
  frontend/src/hooks/useNotify.ts
  frontend/src/pages/BooksCreatePage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/SignupPage.tsx
  frontend/src/redux/slice/alarmSlice.ts
  frontend/src/redux/slice/bookCreateSlice.ts
  frontend/src/redux/slice/notificationSlice.ts
  frontend/src/utils/resizeImage.ts
Labels: 프론트엔드, 리팩토링

#345 [BE] Refactor: review조회 수정 - 도서imageUrl추가
  backend/src/main/java/com/dongnebook/domain/review/dto/response/ReviewResponse.java
  backend/src/main/java/com/dongnebook/domain/review/repository/ReviewQueryRepository.java
Labels: 벡엔드, 기능, 리팩토링

#346 [FE] Feat: 리뷰열람 구현 및 기존 평점을 별점으로 교체
  frontend/src/api/hooks/review/useReviewList.tsx
  frontend/src/api/review.ts
  frontend/src/components/Books/BookDetail.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/History/RentStatusButton.tsx
  frontend/src/components/Merchant/ReviewList.tsx
  frontend/src/components/Review/RatingSelect.tsx
  frontend/src/components/Review/Review.tsx
  frontend/src/components/common/Star.tsx
  frontend/src/pages/MerchantPage.tsx
Labels: 프론트엔드, 기능

#347 [BE] Refactor : 리팩토링 v2
  backend/gradlew
  backend/src/main/java/com/dongnebook/domain/alarm/application/AlarmService.java
  backend/src/main/java/com/dongnebook/domain/alarm/domain/Alarm.java
  backend/src/main/java/com/dongnebook/domain/alarm/exception/AlarmNotFoundException.java
  backend/src/main/java/com/dongnebook/domain/alarm/exception/CanNotSendException.java
  backend/src/main/java/com/dongnebook/domain/alarm/repository/EmitterRepositoryImpl.java
  backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
  backend/src/main/java/com/dongnebook/domain/book/domain/Book.java
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookDetailResponse.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/book/ui/BookController.java
  backend/src/main/java/com/dongnebook/domain/chat/application/ChatService.java
  backend/src/main/java/com/dongnebook/domain/chat/application/RoomService.java
  backend/src/main/java/com/dongnebook/domain/chat/domain/ChatRoom.java
  backend/src/main/java/com/dongnebook/domain/chat/dto/response/ChatMemberResponse.java
  backend/src/main/java/com/dongnebook/domain/chat/dto/response/LastChatResponse.java
  backend/src/main/java/com/dongnebook/domain/chat/repository/ChatRepository.java
  backend/src/main/java/com/dongnebook/domain/chat/repository/RoomRepository.java
  backend/src/main/java/com/dongnebook/domain/chat/ui/RedisSubscriber.java
  backend/src/main/java/com/dongnebook/domain/dibs/domain/Dibs.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
  backend/src/main/java/com/dongnebook/domain/member/dto/request/MemberRegisterRequest.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberExistsCheckResponse.java
  backend/src/main/java/com/dongnebook/domain/member/exception/UnAuthorizedException.java
  backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
  backend/src/main/java/com/dongnebook/domain/model/Location.java
  backend/src/main/java/com/dongnebook/domain/model/image/application/ImageUploadService.java
  backend/src/main/java/com/dongnebook/domain/model/image/dto/ImageUploadRequest.java
  backend/src/main/java/com/dongnebook/domain/model/image/exception/UploadFailed.java
  backend/src/main/java/com/dongnebook/domain/model/image/infrastructure/AwsS3Service.java
  backend/src/main/java/com/dongnebook/domain/model/image/ui/ImageUploadController.java
  backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java
  backend/src/main/java/com/dongnebook/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/dongnebook/global/dto/response/MultiResponse.java
  backend/src/main/java/com/dongnebook/global/error/exception/BusinessException.java
  backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
  backend/src/main/java/com/dongnebook/global/security/auth/filter/JwtVerificationFilter.java
  backend/src/main/java/com/dongnebook/global/security/auth/filter/TokenProvider.java
  backend/src/main/java/com/dongnebook/global/security/auth/handler/MemberAuthenticationEntryPoint.java
  backend/src/main/java/com/dongnebook/global/security/auth/handler/MemberAuthenticationFailureHandler.java
  backend/src/main/java/com/dongnebook/global/security/auth/oauth/OAuthAttributes.java
  backend/src/main/java/com/dongnebook/global/security/auth/oauth/OAuthService.java
  backend/src/main/java/com/dongnebook/global/security/auth/userdetails/CustomUserDetailsService.java
  backend/src/main/java/com/dongnebook/global/test/BulkInsertController.java
  backend/src/main/java/com/dongnebook/global/utils/CustomAuthorityUtils.java
  backend/src/main/java/com/dongnebook/global/utils/Enum.java
  backend/src/test/java/com/dongnebook/domain/rental/application/RentalServiceTest.java
Labels: 벡엔드, 리팩토링

#350 [BE] Refactor: redis 주소 변경
  backend/src/main/resources/application-rds-createdb.yml
  backend/src/main/resources/application-rds.yml
Labels: 벡엔드, 리팩토링, 인프라

#351 [FE] Refactor: 타입 리팩토링
  frontend/src/components/Map/CustomOverlay.tsx
  frontend/src/components/Map/KaKaoMapTypes.ts
  frontend/src/components/Map/KakaoMap.tsx
  frontend/src/components/Map/MerchantLists.tsx
  frontend/src/components/Map/Search.tsx
  frontend/src/components/Merchant/ReviewList.tsx
  frontend/src/components/Review/Review.tsx
  frontend/src/pages/BooksSearchPage.tsx
Labels: 프론트엔드, 리팩토링

#352 [FE] Feat: 타입 리팩토링
  frontend/src/api/hooks/map/useBookList.ts
  frontend/src/api/hooks/map/useMerchantList.ts
  frontend/src/components/Map/BookLists.tsx
  frontend/src/components/Map/KaKaoMapTypes.ts
  frontend/src/components/Map/KakaoMap.tsx
  frontend/src/components/Map/MerchantLists.tsx
  frontend/src/components/Map/Search.tsx
  frontend/src/pages/ReviewCreatePage.tsx
Labels: 프론트엔드, 리팩토링

#353 [FE] Fix : 리뷰 및 리뷰 모달창 css 수정
  frontend/src/components/Merchant/BookList.tsx
  frontend/src/components/Review/Review.tsx
  frontend/src/components/common/BookStatus.tsx
  frontend/src/components/common/ConfirmModal.tsx
Labels: 프론트엔드

#355 [BE] Test : 책 단위 테스트 추가
  backend/build.gradle
  backend/src/main/java/com/dongnebook/domain/alarm/application/AlarmService.java
  backend/src/main/java/com/dongnebook/domain/alarm/domain/Alarm.java
  backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
  backend/src/main/java/com/dongnebook/domain/book/domain/Book.java
  backend/src/main/java/com/dongnebook/domain/book/domain/Money.java
  backend/src/main/java/com/dongnebook/domain/book/dto/request/BookSearchCondition.java
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookDetailResponse.java
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookResponse.java
  backend/src/main/java/com/dongnebook/domain/book/dto/response/BookSimpleResponse.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookCommandRepository.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/dibs/domain/Dibs.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/BookDetailMemberResponse.java
  backend/src/main/java/com/dongnebook/domain/refreshtoken/domain/RefreshToken.java
  backend/src/main/java/com/dongnebook/domain/refreshtoken/repository/RefreshTokenRepository.java
  backend/src/main/java/com/dongnebook/global/security/auth/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/dongnebook/global/security/auth/filter/JwtVerificationFilter.java
  backend/src/main/java/com/dongnebook/global/security/auth/handler/MemberAuthenticationSuccessHandler.java
  backend/src/main/resources/application-rds-createdb.yml
  backend/src/main/resources/application-rds.yml
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/bootstrap.yml
  backend/src/test/java/com/dongnebook/DongnebookApplicationTests.java
  backend/src/test/java/com/dongnebook/config/TestConfig.java
  backend/src/test/java/com/dongnebook/domain/book/application/BookServiceTest.java
  backend/src/test/java/com/dongnebook/domain/book/repository/BookQueryRepositoryTest.java
  backend/src/test/java/com/dongnebook/support/BookStub.java
  backend/src/test/java/com/dongnebook/support/DataClearExtension.java
  backend/src/test/java/com/dongnebook/support/DatabaseCleaner.java
  backend/src/test/java/com/dongnebook/support/LocationStub.java
  backend/src/test/java/com/dongnebook/support/MemberStub.java
Labels: 벡엔드, 테스트
