Repository codestates-seb/seb40_main_015, pull requests merged in 2023-02, with the labels that each got.

#364 [FE] Refactor : 이미지 리사이징 관련 리팩토링
  frontend/src/utils/resizeImage.ts
Labels: 프론트엔드, 리팩토링

#368 refactor : redis설정 추가
  backend/src/main/java/com/dongnebook/global/config/RedisConfig.java
Labels: 기능

#372 Refactor: 리팩토링
  frontend/src/api/hooks/chat/useGetRoomMessage.ts
  frontend/src/api/hooks/user/useUserInfo.ts
  frontend/src/components/Books/BookRentalInfo.tsx
  frontend/src/components/Chat/SendingMessage.tsx
  frontend/src/components/Merchant/BookList.tsx
  frontend/src/components/Review/RatingSelect.tsx
  frontend/src/components/Review/Review.tsx
  frontend/src/components/Review/TextInput.tsx
  frontend/src/components/Review/index.ts
  frontend/src/pages/BooksRentalPage.tsx
  frontend/src/pages/ChatRoom/ChatRoomPage.tsx
  frontend/src/pages/ChatRoom/hooks/useClient.ts
  frontend/src/pages/ChatsPage.tsx
  frontend/src/pages/MerchantPage.tsx
  frontend/src/pages/ReviewCreatePage.tsx
  frontend/src/pages/index.tsx
Labels: 프론트엔드, 리팩토링

#375 [BE] Infra: 배포자동화 범위에 dev브랜치가 포함되도록 수정
  .github/workflows/gradle.yml
Labels: 벡엔드, 인프라

#377 [FE] Chore: yml paths-ignore 옵션 추가
  .github/workflows/client-deploy.yml
Labels: 프론트엔드, 인프라

#374 Refactor: 도서 상세조회 리팩토링
  frontend/src/components/Books/BookRentalInfo.tsx
  frontend/src/pages/BooksRentalPage.tsx
Labels: 프론트엔드, 리팩토링

#378 [BE] Infra : Cloud Watch 연동
  backend/src/main/resources/logback-spring.xml
Labels: 벡엔드, 인프라

#379 [FE] Chore: yml env 속성 추가
  .github/workflows/client-deploy.yml
Labels: 프론트엔드, 버그, 인프라

#380 [FE] Chore: yml env 생성 코드 추가
  .github/workflows/client-deploy.yml
Labels: 프론트엔드, 버그, 인프라

#381 [FE] Refactor: 이미지 alt 속성 추가
  frontend/src/components/Merchant/BookList.tsx
Labels: 프론트엔드, 리팩토링

#383 [FE] Refactor: 채팅 리팩토링
  frontend/src/components/Chat/Message.tsx
  frontend/src/components/Chat/MessageList.tsx
  frontend/src/components/Chat/SendingMessage.tsx
  frontend/src/components/Chat/index.ts
Labels: 프론트엔드, 리팩토링

#384 [FE] Refactor: 채팅 리팩토링
  frontend/src/api/hooks/chat/useGetRoomMessage.ts
  frontend/src/components/Chat/BookInfo.tsx
  frontend/src/components/Chat/ChatLists.tsx
  frontend/src/pages/ChatRoom/ChatRoomPage.tsx
Labels: 프론트엔드, 기능, 리팩토링

#385 [BE] Refactor: review 조회 수정 - reviewerId 응답데이터에 추가
  backend/src/main/java/com/dongnebook/domain/review/dto/response/ReviewResponse.java
  backend/src/main/java/com/dongnebook/domain/review/repository/ReviewQueryRepository.java
Labels: 벡엔드, 기능, 리팩토링

#387 [BE] Refactor: 대여내역 조회 - 필터링 queryString 값 변경
  backend/src/main/java/com/dongnebook/domain/rental/domain/RentalState.java
  backend/src/main/java/com/dongnebook/domain/rental/repository/RentalQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java
Labels: 벡엔드, 기능, 리팩토링

#386 [FE] Feat: 상인정보 리뷰보기, 채팅 변경
  frontend/src/components/Chat/ChatLists.tsx
  frontend/src/components/Chat/Message.tsx
  frontend/src/components/Merchant/BookList.tsx
  frontend/src/components/Merchant/ReviewList.tsx
Labels: 프론트엔드, 기능, 리팩토링

#388 [BE] Infra: AWS CodeDeploy Setting - OneAtATime
  .github/workflows/gradle.yml
Labels: 벡엔드, 인프라

#389 [BE] Infra: logback-spring.xml 파일 수정
  backend/src/main/resources/logback-spring.xml
Labels: 벡엔드, 리팩토링, 인프라
