Repository codestates-seb/seb40_main_015, pull requests merged in 2023-04, with the labels that each got.

#426 [BE] Test : chat 단위 테스트 추가
  backend/src/main/java/com/dongnebook/domain/book/application/BookQueryService.java
  backend/src/main/java/com/dongnebook/domain/chat/domain/ChatMessage.java
  backend/src/main/java/com/dongnebook/domain/chat/domain/ChatRoom.java
  backend/src/main/java/com/dongnebook/domain/chat/repository/ChatRepository.java
  backend/src/main/java/com/dongnebook/domain/chat/ui/ChatController.java
  backend/src/test/java/com/dongnebook/config/TestConfig.java
  backend/src/test/java/com/dongnebook/domain/book/application/BookProductPostServiceTest.java
  backend/src/test/java/com/dongnebook/domain/chat/application/ChatServiceTest.java
  backend/src/test/java/com/dongnebook/domain/chat/application/RoomServiceTest.java
  backend/src/test/java/com/dongnebook/domain/chat/controller/ChatControllerTest.java
  backend/src/test/java/com/dongnebook/domain/chat/repository/ChatRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/chat/repository/RoomRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/rental/application/RentalServiceTest.java
Labels: 벡엔드, 테스트

#427 [BE] Test: Alarm Domain API Layer Unit Test
  backend/src/test/java/com/dongnebook/domain/alarm/ui/AlarmControllerTest.java
Labels: 벡엔드, 테스트

#428 [BE] Test: AlarmDomain Service Layer Unit Test
  backend/src/test/java/com/dongnebook/domain/alarm/application/AlarmReadServiceTest.java
  backend/src/test/java/com/dongnebook/domain/alarm/application/AlarmServiceTest.java
Labels: 벡엔드, 테스트

#429 [BE] Test: AlarmQueryRepository Unit Test
  backend/src/test/java/com/dongnebook/config/TestConfig.java
  backend/src/test/java/com/dongnebook/domain/alarm/repository/AlarmQueryRepositoryTest.java
Labels: 벡엔드, 테스트

#430 [BE] Test : 단위 테스트 추가
  .github/workflows/testAfterPR.yml
  backend/src/main/java/com/dongnebook/domain/chat/ui/RedisSubscriber.java
  backend/src/main/java/com/dongnebook/domain/model/image/infrastructure/AwsS3Service.java
  backend/src/main/java/com/dongnebook/domain/model/image/infrastructure/DefaultImageIOService.java
  backend/src/main/java/com/dongnebook/domain/model/image/infrastructure/ImageIOService.java
  backend/src/main/java/com/dongnebook/domain/model/image/infrastructure/TestImageIOService.java
  backend/src/main/java/com/dongnebook/domain/model/image/ui/ImageUploadController.java
  backend/src/main/java/com/dongnebook/global/config/SecurityConfig.java
  backend/src/main/java/com/dongnebook/global/infra/KaKaoBookInfoFetcher.java
  backend/src/main/java/com/dongnebook/global/security/auth/oauth/OAuthAttributes.java
  backend/src/main/java/com/dongnebook/global/security/auth/oauth/OAuthService.java
  backend/src/main/java/com/dongnebook/global/security/auth/oauth/OAuthUserProfile.java
  backend/src/test/java/com/dongnebook/domain/chat/controller/RedisPublisherTest.java
  backend/src/test/java/com/dongnebook/domain/chat/controller/RedisSubscriberTest.java
  backend/src/test/java/com/dongnebook/domain/model/image/infrastructure/AwsS3ServiceTest.java
  backend/src/test/java/com/dongnebook/domain/model/image/infrastructure/JavaImageResizerTest.java
  backend/src/test/java/com/dongnebook/domain/model/image/infrastructure/TestImageResizer.java
  backend/src/test/java/com/dongnebook/domain/model/image/ui/ImageUploadControllerTest.java
  backend/src/test/java/com/dongnebook/global/GBookInfoParserTest.java
  backend/src/test/java/com/dongnebook/global/KakaoBookInfoFetcherTest.java
  backend/src/test/resources/application-API-KEY.yml
  backend/src/test/resources/application.yml
Labels: 벡엔드, 테스트

#431 [BE] fix : KaKaoBookInfoFetcher 수정
  backend/src/main/java/com/dongnebook/global/infra/KaKaoBookInfoFetcher.java
Labels: 벡엔드, 버그

#434 [BE] Test: MemberQueryRepository Unit Test
  backend/src/test/java/com/dongnebook/domain/member/repository/MemberQueryRepositoryTest2.java
Labels: 벡엔드, 테스트

#435 [BE] Test: EmitterRepositoryImpl modify & Unit Test
  backend/src/main/java/com/dongnebook/domain/alarm/repository/EmitterRepositoryImpl.java
  backend/src/test/java/com/dongnebook/domain/alarm/repository/EmitterRepositoryImplTest.java
Labels: 벡엔드, 리팩토링, 테스트

#436 [FE] Refactor: 코드 리팩토링
  frontend/src/api/hooks/auth/useAuthRenew.ts
  frontend/src/components/Books/BookCalendar.tsx
  frontend/src/components/Chat/BookInfo.tsx
  frontend/src/components/History/LendBookLists.tsx
  frontend/src/components/History/LendBookUserInfo.tsx
  frontend/src/components/History/RentBookLists.tsx
  frontend/src/components/History/RentStatusButton.tsx
  frontend/src/components/common/Modal.tsx
  frontend/src/components/common/NavBar.tsx
  frontend/src/components/common/Title.tsx
  frontend/src/hooks/useAPI.ts
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/pages/ReviewCreatePage.tsx
Labels: 프론트엔드, 리팩토링

#440 [BE] Feat: Add getReservationAvailability API
  backend/src/main/java/com/dongnebook/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/dongnebook/domain/reservation/ui/ReservationsController.java
  backend/src/test/java/com/dongnebook/domain/reservation/service/ReservationServiceTest.java
  backend/src/test/java/com/dongnebook/domain/reservation/ui/ReservationControllerTest.java
Labels: 벡엔드, 기능, 테스트

#439 [FE] Feat: 스토리북 컴포넌트 추가
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/hooks/merchant/useMerchantBookList.ts
  frontend/src/components/Login/Oauth.tsx
  frontend/src/components/Login/index.ts
  frontend/src/components/Map/KakaoMap.tsx
  frontend/src/components/Review/RatingSelect.tsx
  frontend/src/components/common/NavBar.tsx
  frontend/src/components/common/Oauth.tsx
  frontend/src/components/common/PcVersion/Header/Header.tsx
  frontend/src/components/common/PcVersion/Header/Logo.tsx
  frontend/src/components/common/index.ts
  frontend/src/hooks/useGeoLocation.ts
  frontend/src/pages/BooksSearchPage.tsx
  frontend/src/stories/Button.stories.tsx
  frontend/src/stories/Header.stories.ts
  frontend/src/stories/Input.stories.ts
  frontend/src/stories/NavBar.stories.ts
  frontend/src/stories/Review/RatingSelect.stories.tsx
  frontend/src/stories/Star.stories.ts
  frontend/yarn.lock
Labels: 프론트엔드, 리팩토링

#441 [BE] Refactor: Modify checkReservationAvailability API
  backend/src/main/java/com/dongnebook/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/dongnebook/domain/reservation/ui/ReservationsController.java
  backend/src/test/java/com/dongnebook/domain/reservation/service/ReservationServiceTest.java
  backend/src/test/java/com/dongnebook/domain/reservation/ui/ReservationControllerTest.java
Labels: 벡엔드, 기능, 리팩토링, 테스트

#443 [BE] Fix : 리뷰조회시 도서명이 비어있던 이슈 해결
  backend/build.gradle
  backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
  backend/src/main/java/com/dongnebook/domain/review/dto/response/ReviewResponse.java
  backend/src/main/java/com/dongnebook/domain/review/repository/ReviewQueryRepository.java
  backend/src/main/java/com/dongnebook/global/error/exception/CanNotChangeStateException.java
  backend/src/test/java/com/dongnebook/DongnebookApplicationTests.java
  backend/src/test/java/com/dongnebook/config/TestConfig.java
  backend/src/test/java/com/dongnebook/domain/alarm/application/AlarmReadServiceTest.java
  backend/src/test/java/com/dongnebook/domain/alarm/application/AlarmServiceTest.java
  backend/src/test/java/com/dongnebook/domain/alarm/repository/AlarmQueryRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/alarm/repository/EmitterRepositoryImplTest.java
  backend/src/test/java/com/dongnebook/domain/alarm/ui/AlarmControllerTest.java
  backend/src/test/java/com/dongnebook/domain/book/repository/BookQueryRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/chat/repository/RoomRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/dibs/application/DibsServiceTest.java
  backend/src/test/java/com/dongnebook/domain/dibs/repository/DibsRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/dibs/ui/DibsControllerTest.java
  backend/src/test/java/com/dongnebook/domain/member/repository/MemberQueryRepository2Test.java
  backend/src/test/java/com/dongnebook/domain/rental/application/RentalService2Test.java
  backend/src/test/java/com/dongnebook/domain/rental/repository/RentalQueryRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/rental/repository/RentalRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/rental/ui/RentalControllerTest.java
  backend/src/test/java/com/dongnebook/domain/reservation/repository/ReservationQueryRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/reservation/repository/ReservationRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/reservation/service/ReservationServiceTest.java
  backend/src/test/java/com/dongnebook/domain/reservation/ui/ReservationControllerTest.java
  backend/src/test/java/com/dongnebook/domain/review/application/ReviewServiceTest.java
  backend/src/test/java/com/dongnebook/domain/review/repository/ReviewQueryRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/review/repository/ReviewRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/review/ui/ReviewControllerTest.java
  backend/src/test/java/com/dongnebook/global/GBookInfoParserTest.java
  backend/src/test/java/com/dongnebook/global/test/HelloControllerTest.java
Labels: 벡엔드, 리팩토링, 버그
