Repository codestates-seb/seb40_main_015, pull requests merged in 2023-03, with the labels that each got.

#390 Feat : DB replication
  backend/build.gradle
  backend/src/main/java/com/dongnebook/domain/alarm/dto/AlarmResponse.java
  backend/src/main/java/com/dongnebook/domain/alarm/repository/EmitterRepositoryImpl.java
  backend/src/main/java/com/dongnebook/domain/book/domain/BookState.java
  backend/src/main/java/com/dongnebook/domain/book/dto/response/KaKaoBookInfoResponse.java
  backend/src/main/java/com/dongnebook/domain/chat/dto/response/ChatResponse.java
  backend/src/main/java/com/dongnebook/domain/chat/dto/response/ChatRoomResponse.java
  backend/src/main/java/com/dongnebook/domain/chat/ui/RedisPublisher.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/dto/request/MemberEditRequest.java
  backend/src/main/java/com/dongnebook/domain/member/dto/request/MerchantSearchRequest.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberDetailResponse.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberLoginResponse.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberResponse.java
  backend/src/main/java/com/dongnebook/domain/member/repository/MemberQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
  backend/src/main/java/com/dongnebook/domain/model/image/dto/ImageUploadRequest.java
  backend/src/main/java/com/dongnebook/domain/rental/application/RentalCreateEvent.java
  backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
  backend/src/main/java/com/dongnebook/domain/rental/dto/request/RentalSearchCondition.java
  backend/src/main/java/com/dongnebook/global/config/WebSocketConfig.java
  backend/src/main/java/com/dongnebook/global/dto/request/SearchRequest.java
  backend/src/main/java/com/dongnebook/global/replication/CircularList.java
  backend/src/main/java/com/dongnebook/global/replication/CustomDataSourceConfig.java
  backend/src/main/java/com/dongnebook/global/replication/CustomDataSourceProperties.java
  backend/src/main/java/com/dongnebook/global/replication/ReplicationRoutingDataSource.java
  backend/src/main/java/com/dongnebook/global/security/auth/exception/AccessTokenNotFound.java
  backend/src/main/java/com/dongnebook/global/security/auth/userdetails/AuthMember.java
  backend/src/main/resources/application-rds.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/dongnebook/DongnebookApplicationTests.java
  backend/src/test/java/com/dongnebook/config/TestConfig.java
  backend/src/test/java/com/dongnebook/domain/member/application/MemberServiceTest.java
  backend/src/test/java/com/dongnebook/domain/member/repository/MemberQueryRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/rental/application/RentalServiceTest.java
  backend/src/test/resources/application.yml
Labels: 벡엔드, 기능

#393 [BE] Refactor : replication 설정 수정
  backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
  backend/src/main/java/com/dongnebook/global/replication/CustomDataSourceConfig.java
  backend/src/main/java/com/dongnebook/global/replication/CustomDataSourceProperties.java
  backend/src/main/java/com/dongnebook/global/replication/ReplicationRoutingDataSource.java
  backend/src/main/resources/application-rds.yml
Labels: 벡엔드, 리팩토링

#397 [BE] Fix : pageRequest 오타 수정
  backend/src/main/java/com/dongnebook/global/dto/request/PageRequestImpl.java
Labels: 벡엔드, 버그

#398 [BE] Refactor: 불필요 항목 git 대상에서 제외
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/seb40_main_backend.iml
  .idea/sonarlint/issuestore/3/0/30280c462dfa27bf2dca59e2b7d560096833ab88
  .idea/sonarlint/issuestore/4/6/467d5adac1adea8f63676aa644f8f716a01e9a7d
  .idea/sonarlint/issuestore/6/1/61e420080e0d6359f64ee522854f9a0668262802
  .idea/sonarlint/issuestore/6/4/64e5db7b24a434f59a13d72784d1778e440e440b
  .idea/sonarlint/issuestore/8/3/83d41337d0843e30b85becc1cdc44b0c71a4fb72
  .idea/sonarlint/issuestore/b/0/b02b324e8033c63314787d86c33da6a439363086
  .idea/sonarlint/issuestore/e/4/e498cdd02ea58a123383d95b74efe9eba356dd9a
  .idea/sonarlint/issuestore/e/9/e95e97d89e71c1d6014b7bf3e2a87d694bf6fd89
  .idea/sonarlint/issuestore/e/b/ebb7b4617ba5739bfd58c4f2b4288963319c27f7
  .idea/sonarlint/issuestore/e/d/ed66c02e4cad5fc182c16ab0a24bc33ccebd6b27
  .idea/sonarlint/issuestore/f/9/f931455319b0adc0f61a2a8c36104816977f66cb
  .idea/sonarlint/issuestore/index.pb
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/workspace.xml
  backend/src/main/generated/com/dongnebook/domain/alarm/domain/QAlarm.java
  backend/src/main/generated/com/dongnebook/domain/alarm/dto/QAlarmResponse.java
  backend/src/main/generated/com/dongnebook/domain/book/domain/QBook.java
  backend/src/main/generated/com/dongnebook/domain/book/domain/QMoney.java
  backend/src/main/generated/com/dongnebook/domain/chat/domain/QChatMessage.java
  backend/src/main/generated/com/dongnebook/domain/chat/domain/QChatRoom.java
  backend/src/main/generated/com/dongnebook/domain/dibs/domain/QDibs.java
  backend/src/main/generated/com/dongnebook/domain/member/domain/QMember.java
  backend/src/main/generated/com/dongnebook/domain/member/dto/response/QMemberDetailResponse.java
  backend/src/main/generated/com/dongnebook/domain/member/dto/response/QMemberResponse.java
  backend/src/main/generated/com/dongnebook/domain/model/QBaseTimeEntity.java
  backend/src/main/generated/com/dongnebook/domain/model/QLocation.java
  backend/src/main/generated/com/dongnebook/domain/refreshtoken/domain/QRefreshToken.java
  backend/src/main/generated/com/dongnebook/domain/rental/domain/QRental.java
  backend/src/main/generated/com/dongnebook/domain/rental/dto/response/QRentalBookResponse.java
  backend/src/main/generated/com/dongnebook/domain/rental/dto/response/QRentalInfoResponse.java
  backend/src/main/generated/com/dongnebook/domain/reservation/domain/QReservation.java
  backend/src/main/generated/com/dongnebook/domain/reservation/dto/response/QReservationInfoResponse.java
  backend/src/main/generated/com/dongnebook/domain/reservation/dto/response/QReservationResponse.java
  backend/src/main/generated/com/dongnebook/domain/review/domain/QReview.java
  backend/src/main/generated/com/dongnebook/domain/review/dto/response/QReviewResponse.java
Labels: 벡엔드, 리팩토링

#399 [BE] Infra: EC2 error log Slack alarm
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-spring-local.xml
  backend/src/main/resources/logback-spring.xml
Labels: 벡엔드, 리팩토링, 인프라

#400 [BE] Infra: Infra: EC2 error log Slack alarm - modify
  backend/.gitignore
  backend/build.gradle
  backend/src/main/resources/logback-spring.xml
Labels: 벡엔드, 리팩토링, 인프라

#402 [BE] Infra: error log slack alarm modify
  backend/src/main/resources/logback-spring.xml
Labels: 벡엔드, 리팩토링, 인프라

#403 [BE] Infra: EC2 error log Slack alarm - modify
  backend/src/main/resources/logback-spring.xml
Labels: 벡엔드, 리팩토링, 인프라

#404 [BE] Infra: error log slack alarm configuration edit
  .github/workflows/gradle.yml
  backend/src/main/resources/application-rds.yml
  backend/src/main/resources/logback-spring.xml
Labels: 벡엔드, 리팩토링, 인프라

#405 [BE] Refactor : 카카오api로 책 가져오는 로직 분리
  backend/src/main/java/com/dongnebook/domain/book/adapter/in/BookController.java
  backend/src/main/java/com/dongnebook/domain/book/adapter/in/BookInfoFetcher.java
  backend/src/main/java/com/dongnebook/domain/book/adapter/in/BookInfoParser.java
  backend/src/main/java/com/dongnebook/domain/book/application/port/in/response/ApiBookInfoResponse.java
  backend/src/main/java/com/dongnebook/global/infra/GsonBookInfoParser.java
  backend/src/main/java/com/dongnebook/global/infra/KaKaoBookInfoFetcher.java
Labels: 벡엔드, 리팩토링

#406 [BE] Infra: modify workflow - divide build & test role
  .github/workflows/gradle.yml
Labels: 벡엔드, 인프라, 테스트

#407 [BE] Test: UnitTest - HelloController
  backend/src/main/java/com/dongnebook/global/test/HelloController.java
  backend/src/test/java/com/dongnebook/domain/helloSample/ui/HelloControllerTest.java
  backend/src/test/java/com/dongnebook/global/test/HelloControllerTest.java
Labels: 벡엔드, 테스트

#408 [BE] Infra: modify workflow - Add test working directory
  .github/workflows/gradle.yml
Labels: 벡엔드, 리팩토링, 인프라

#409 [BE] Fix :로그인안되는문제 수정
  backend/src/main/java/com/dongnebook/domain/book/adapter/in/BookController.java
  backend/src/main/java/com/dongnebook/domain/book/adapter/out/BookQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/book/application/BookCommandService.java
  backend/src/main/java/com/dongnebook/domain/book/application/BookQueryService.java
  backend/src/main/java/com/dongnebook/domain/book/application/port/in/request/BookPostEditCommand.java
  backend/src/main/java/com/dongnebook/domain/book/application/port/in/request/BookPostRegisterCommand.java
  backend/src/main/java/com/dongnebook/domain/book/application/port/in/request/BookSearchCommand.java
  backend/src/main/java/com/dongnebook/domain/book/application/port/in/request/SearchCommand.java
  backend/src/main/java/com/dongnebook/domain/book/application/port/in/response/BookResponse.java
  backend/src/main/java/com/dongnebook/domain/book/domain/Book.java
  backend/src/main/java/com/dongnebook/domain/dibs/service/DibsService.java
  backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
  backend/src/main/java/com/dongnebook/domain/rental/domain/Rental.java
  backend/src/main/resources/application.yml
Labels: 벡엔드, 버그

#410 [BE] Infra: modify workflow - publish unit test report
  .github/workflows/gradle.yml
  backend/src/main/resources/application.yml
Labels: 벡엔드, 인프라, 테스트

#412 [BE] Infra: modify workflow - modify permissions
  .github/workflows/gradle.yml
  backend/src/main/resources/application.yml
Labels: 벡엔드, 리팩토링, 인프라, 테스트

#413 [BE] Test: Add jacoco report XML
  backend/build.gradle
Labels: 벡엔드, 테스트

#414 [BE] Infra: Add test after PR in Github
  .github/workflows/testAfterPR.yml
Labels: 벡엔드, 인프라, 테스트

#416 [BE] Infra: modify PRTestWorkflow
  .github/workflows/testAfterPR.yml
Labels: 벡엔드, 리팩토링, 인프라

#417 [BE] Infra: modify buildWorkflow
  .github/workflows/gradle.yml
  .github/workflows/testAfterPR.yml
Labels: 벡엔드, 인프라

#418 [BE] Test: Rental domain unit test
  backend/src/test/java/com/dongnebook/config/TestConfig.java
  backend/src/test/java/com/dongnebook/domain/rental/application/RentalServiceTest2.java
  backend/src/test/java/com/dongnebook/domain/rental/repository/RentalQueryRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/rental/repository/RentalRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/rental/ui/RentalControllerTest.java
Labels: 벡엔드, 테스트

#419 [BE] Test : Reservation Domain UnitTest
  backend/src/test/java/com/dongnebook/config/TestConfig.java
  backend/src/test/java/com/dongnebook/domain/reservation/repository/ReservationQueryRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/reservation/repository/ReservationRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/reservation/service/ReservationServiceTest.java
  backend/src/test/java/com/dongnebook/domain/reservation/ui/ReservationControllerTest.java
Labels: 벡엔드, 테스트

#421 [BE] Refactor: 테스트 관련 리팩토링 & CI/CD 관련 설정 수정
  .github/workflows/gradle.yml
  .github/workflows/testAfterPR.yml
  backend/build.gradle
  backend/lombok.config
  backend/src/main/java/com/dongnebook/domain/rental/repository/RentalQueryRepository.java
  backend/src/test/java/com/dongnebook/domain/rental/application/RentalServiceTest2.java
  backend/src/test/java/com/dongnebook/domain/rental/repository/RentalQueryRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/rental/repository/RentalRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/reservation/repository/ReservationQueryRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/reservation/repository/ReservationRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/review/repository/ReviewQueryRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/review/repository/ReviewRepositoryTest.java
Labels: 벡엔드, 리팩토링, 인프라, 테스트

#422 [BE] Refactor: modify reviewQueryRerepository & test
  backend/src/main/java/com/dongnebook/domain/book/domain/Book.java
  backend/src/main/java/com/dongnebook/domain/rental/domain/Rental.java
  backend/src/main/java/com/dongnebook/domain/review/dto/response/ReviewResponse.java
  backend/src/main/java/com/dongnebook/domain/review/repository/ReviewQueryRepository.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/dongnebook/domain/review/repository/ReviewQueryRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/review/ui/ReviewControllerTest.java
Labels: 벡엔드, 기능, 리팩토링, 테스트

#423 [BE] Refactor: Modify Rental, Reservation & Review Domain API Response Verification
  backend/src/test/java/com/dongnebook/domain/rental/ui/RentalControllerTest.java
  backend/src/test/java/com/dongnebook/domain/reservation/ui/ReservationControllerTest.java
  backend/src/test/java/com/dongnebook/domain/review/ui/ReviewControllerTest.java
Labels: 벡엔드, 리팩토링, 테스트

#425 [BE] Test : Dibs domain unit Test
  backend/src/test/java/com/dongnebook/domain/dibs/application/DibsServiceTest.java
  backend/src/test/java/com/dongnebook/domain/dibs/repository/DibsRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/dibs/ui/DibsControllerTest.java
Labels: 벡엔드, 테스트
