Repository codestates-seb/seb40_main_015, pull requests merged in 2023-01, with the labels that each got.

#354 [FE] Refactor: 절대경로 설정 추가 & 컴포넌트 index 파일 생성
  frontend/src/api/auth.ts
  frontend/src/api/books.ts
  frontend/src/api/createBook.ts
  frontend/src/api/history.ts
  frontend/src/api/hooks/auth/useAuthRenew.ts
  frontend/src/api/hooks/books/useGetBookDetail.ts
  frontend/src/api/hooks/common/useGetPhotoUrl.tsx
  frontend/src/api/hooks/createBooks/usePostBooks.tsx
  frontend/src/api/hooks/history/useBookReturn.ts
  frontend/src/api/hooks/history/useCancelByCustomer.ts
  frontend/src/api/hooks/history/useCancelByMerchant.ts
  frontend/src/api/hooks/notice/useDeleteNotice.tsx
  frontend/src/api/hooks/notice/useGetNotice.tsx
  frontend/src/api/hooks/user/useUserInfo.ts
  frontend/src/api/index.ts
  frontend/src/api/instance.ts
  frontend/src/api/map.ts
  frontend/src/components/Books/BookDetail.tsx
  frontend/src/components/Books/index.ts
  frontend/src/components/BooksCreate/index.ts
  frontend/src/components/Chat/index.ts
  frontend/src/components/HeroSection/index.ts
  frontend/src/components/History/index.ts
  frontend/src/components/Loading/index.ts
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/Login/index.ts
  frontend/src/components/LoginOnly/LoginOnlyLayout.tsx
  frontend/src/components/LoginOnly/index.ts
  frontend/src/components/Map/index.ts
  frontend/src/components/Member/index.ts
  frontend/src/components/Merchant/index.ts
  frontend/src/components/Notice/index.ts
  frontend/src/components/Review/index.ts
  frontend/src/components/SignUp/index.ts
  frontend/src/components/common/index.ts
  frontend/src/components/index.ts
  frontend/src/pages/BooksBookingPage.tsx
  frontend/src/pages/BooksCreatePage.tsx
  frontend/src/pages/BooksDetailPage.tsx
  frontend/src/pages/BooksPage.tsx
  frontend/src/pages/BooksRentalPage.tsx
  frontend/src/pages/BooksSearchPage.tsx
  frontend/src/pages/ChatRoomPage.tsx
  frontend/src/pages/ChatsPage.tsx
  frontend/src/pages/HistoryPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MerchantPage.tsx
  frontend/src/pages/NoticePage.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/pages/ReviewCreateMessages.tsx
  frontend/src/pages/ReviewCreatePage.tsx
  frontend/src/pages/SignupPage.tsx
  frontend/src/pages/index.tsx
  frontend/tsconfig.json
Labels: 프론트엔드, 리팩토링

#356 [BE] Test: MemberService 단위 테스트
  backend/build.gradle
  backend/src/main/java/com/dongnebook/domain/book/domain/Book.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/dto/request/MerchantSearchRequest.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberDetailResponse.java
  backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberResponse.java
  backend/src/main/java/com/dongnebook/domain/member/exception/MemberHasOnLoanException.java
  backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
  backend/src/main/java/com/dongnebook/domain/rental/repository/RentalQueryRepository.java
  backend/src/main/java/com/dongnebook/global/security/auth/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/dongnebook/global/security/auth/filter/JwtVerificationFilter.java
  backend/src/main/java/com/dongnebook/global/security/auth/filter/TokenProvider.java
  backend/src/test/java/com/dongnebook/domain/book/repository/BookQueryRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/member/application/MemberServiceTest.java
  backend/src/test/java/com/dongnebook/support/BookStub.java
  backend/src/test/java/com/dongnebook/support/MemberStub.java
Labels: 벡엔드, 리팩토링, 테스트

#358 [BE] Feat : 이미지 리사이징
  backend/src/main/java/com/dongnebook/domain/model/image/application/ImageUploadService.java
  backend/src/main/java/com/dongnebook/domain/model/image/infrastructure/AwsS3Service.java
  backend/src/main/java/com/dongnebook/domain/model/image/ui/ImageUploadController.java
Labels: 벡엔드, 기능

#357 [BE] Test : 회원 영속계층 단위테스트작성
  backend/src/main/java/com/dongnebook/domain/book/dto/request/BookRegisterRequest.java
  backend/src/main/java/com/dongnebook/domain/chat/dto/request/RoomRequest.java
  backend/src/main/java/com/dongnebook/domain/member/dto/request/MemberEditRequest.java
  backend/src/main/java/com/dongnebook/domain/member/dto/request/MerchantSearchRequest.java
  backend/src/main/java/com/dongnebook/domain/model/image/dto/ImageUploadRequest.java
  backend/src/main/java/com/dongnebook/domain/rental/dto/request/RentalSearchCondition.java
  backend/src/main/java/com/dongnebook/domain/review/dto/request/ReviewRequest.java
  backend/src/test/java/com/dongnebook/config/TestConfig.java
  backend/src/test/java/com/dongnebook/domain/book/repository/BookQueryRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/member/repository/MemberQueryRepositoryTest.java
Labels: 벡엔드, 테스트

#359 [BE] Bug : 로그인 이슈 해결
  backend/src/main/java/com/dongnebook/domain/book/dto/request/BookEditRequest.java
  backend/src/main/java/com/dongnebook/domain/book/dto/request/BookSearchCondition.java
  backend/src/main/java/com/dongnebook/domain/chat/dto/request/RoomRequest.java
  backend/src/main/java/com/dongnebook/domain/member/dto/request/MerchantSearchRequest.java
  backend/src/main/java/com/dongnebook/domain/model/image/dto/ImageUploadRequest.java
  backend/src/test/java/com/dongnebook/domain/book/application/BookServiceTest.java
  backend/src/test/java/com/dongnebook/domain/book/repository/BookQueryRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/member/repository/MemberQueryRepositoryTest.java
Labels: 벡엔드, 버그

#360 Feat : 리사이징 문제 해결
  backend/src/main/java/com/dongnebook/domain/model/image/infrastructure/AwsS3Service.java
Labels: 벡엔드, 버그

#361 [BE] Refactor : 리팩토링 v3
  backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
  backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/book/ui/BookController.java
  backend/src/main/java/com/dongnebook/domain/chat/application/RoomService.java
  backend/src/main/java/com/dongnebook/domain/chat/repository/ChatRepository.java
  backend/src/main/java/com/dongnebook/domain/chat/ui/ChatController.java
  backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
  backend/src/main/java/com/dongnebook/domain/member/repository/MemberQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/rental/repository/RentalQueryRepository.java
  backend/src/main/java/com/dongnebook/domain/review/application/ReviewService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/dongnebook/domain/book/application/BookServiceTest.java
  backend/src/test/java/com/dongnebook/domain/book/repository/BookQueryRepositoryTest.java
  backend/src/test/java/com/dongnebook/domain/member/application/MemberServiceTest.java
Labels: 벡엔드, 리팩토링
